### ISSUE TITLE
怎么获取上传成功后的图片的地址啊

### ISSUE THREAD

**Issue by liuyunclouder** [aliyun/aliyun-oss-ios-sdk#1]
debug了半天都没看出是怎么获取，API里也没看出有什么方法

![image](https://cloud.githubusercontent.com/assets/1249065/9985156/af9d0c0c-6058-11e5-90e2-09abb8320f93.png)

**Comment by xuyecan** [comment]
意思是指，上传文件以后，获得图片的访问链接吗？这个链接是需要根据bucketname和objectkey另行构造的，目前SDK还没添加这个功能，近期就会加入。

如果图片是允许公共访问，直接拼接http://bucketname.oss-cn-****.aliyuncs.com/objectkey就可以了。

**Comment by liuyunclouder** [comment]
多谢及时回复，期待尽快更新

**Comment by xuyecan** [comment]
已经加入这个功能，更新pod到最新代码即可。
OSSClient.h:

- (BFTask *)presignConstrainURLWithBucketName:(NSString *)bucketName
                                withObjectKey:(NSString *)objectKey
                       withExpirationInterval:(NSTimeInterval)interval;

- (BFTask *)presignPublicURLWithBucketName:(NSString *)bucketName
                            withiObjectKey:(NSString *)objectKey;

用法参考test中的presign cases。

**Comment by liuyunclouder** [comment]
OK
