### ISSUE TITLE
resumableUploadFile完成回调错误

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#10]
以下在resumableUploadFile的回调是错的, 有的task可能被取消了, 

     if (task.error) {
        onComplete(NO, task.error);
    } else {
        onComplete(YES, nil);
    }

不能仅仅通过task.error去判断是否上传成功, 正确的判断应该是:

    completed = YES; cancelled = NO; faulted = NO

麻烦你们修复一下. 谢谢. 

这个Bug我已经在你们的demo工程中提了.

**Comment by xuyecan** [comment]
你好，已做修复。见 [#a46d1a0](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/a46d1a06a51a90790f82c8706095d407754f33ac) 。
