### ISSUE TITLE
multipartUpload 不能跟其他 upload 同时进行

### ISSUE THREAD

**Issue by li6185377** [aliyun/aliyun-oss-ios-sdk#103]
OSSMultipartUploadRequest 需要独立上传。 如果跟其他Request(包括自己) 同时进行，会报各种错误

**Comment by 1019272778** [comment]
@li6185377 您好。请问具体的错误信息是什么？

**Comment by li6185377** [comment]
uploadId 不对之类的。     - (void)testMultipartUpload_normal  方法内，不调用 waitUntilFinished， 同时创建多个 Task 进行上传，

**Comment by 1019272778** [comment]
@li6185377 请问是对同一个文件进行分片上传吗？能否贴一些代码看看呢？

**Comment by duan007a** [comment]
@li6185377 请参考https://github.com/aliyun/aliyun-oss-ios-sdk/commit/2ad028877755784a63be5a1cfb171092c5fd813d
