### ISSUE TITLE
uploadProgress 没有回调

### ISSUE THREAD

**Issue by iDivines** [aliyun/aliyun-oss-ios-sdk#106]
文件可以上传成功，但是 uploadProgress 这个block没有回调

**Comment by 1019272778** [comment]
@iDivines 能帮忙贴一些你的使用代码吗？

**Comment by duan007a** [comment]
@iDivines 你好，请问你的问题有得到解决没？如果没有，请提供一下你使用的sdk版本号以及API，我们也好排查你遇到的问题~

**Comment by iDivines** [comment]
@duan007a 非常感谢您的回复，我用的2.7.1，代码如下,基本就是按照文档写的 https://help.aliyun.com/document_detail/32058.html?spm=5176.doc32056.6.718.TZB8Pi

   OSSPutObjectRequest * put = [OSSPutObjectRequest new];
    put.bucketName = videoAuth.address.bucketName;
    put.objectKey = videoAuth.address.objectKey;
    put.uploadingFileURL = [NSURL fileURLWithPath:file.localPath.absolutePaths];
    put.uploadProgress = ^(int64_t bytesSent, int64_t totalByteSent, int64_t totalBytesExpectedToSend) {
        CGFloat prog = (CGFloat)totalByteSent / (CGFloat)totalBytesExpectedToSend;
        updateFileStatusBlock(prog, file);
    };
    
    OSSTask * putTask = [ossClient putObject:put];
    [putTask continueWithBlock:^id(OSSTask *task) {
    }]

**Comment by duan007a** [comment]
@iDivines 您好，我这边测试case时block都可以执行到。有可能是和iOS sdk版本有关，需要您帮忙调试一下：在OSSNetworking.m中搜索delegate.uploadProgress(bytesSent, totalBytesSent, totalBytesExpectedToSend)并在找到的代码行添加断点，然后尝试上传文件，如果整个回调方法都没有被调用到，请到OSSNetworking.h的134行添加遵循的协议NSURLSessionTaskDelegate，然后再尝试上传操作

**Comment by duan007a** [comment]
@iDivines 问题解决了没有，或者请您更新到最新release版本试一下

**Comment by iDivines** [comment]
@1019272778 非常感谢您的帮助，这几天我一直在调试这个问题，我调试方法发现代理方法didCompleteWithError是有回调的，但是didSendBodyData没有回调。

**Comment by jumpingfrog0** [comment]
<img width="1043" alt="WX20220418-203029@2x" src="https://user-images.githubusercontent.com/7556575/163808696-51563450-b71f-40a7-ba60-692b4a402e2f.png">
@duan007a pod 'AliyunOSSiOS', '2.10.8' 我是用这个版本 uploadProgress 没有回调
