### ISSUE TITLE
download时采用保存为文件方式时可以保存，但保存为NSData为null

### ISSUE THREAD

**Issue by stlemon** [aliyun/aliyun-oss-ios-sdk#107]
RT，，谢谢！

**Comment by duan007a** [comment]
你好，请提供一下你使用的sdk版本号和使用sdk中的API名称

**Comment by duan007a** [comment]
@stlemon 你好，请提供一下你使用中出现问题sdk的版本号和API名称，我们这边验证一下

**Comment by stlemon** [comment]
@duan007a 你好，sdk version：

**Comment by stlemon** [comment]
@duan007a 你好
sdk version：OSS_IOS_SDK_VERSION 2.5.2
API：- (OSSTask *)continueWithBlock:(OSSContinuationBlock)block;

**Comment by duan007a** [comment]
@stlemon 你好，使用API:getObject下载文件时，如果设置了以文件方式保存返回数据的话，在task回调的result对象里面的downloadedData是不存储数据的

**Comment by stlemon** [comment]
@duan007a 那我再看看吧，谢谢了。
