### ISSUE TITLE
OSSClient多实例上传会死锁

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#11]
使用resumableUploadFile  创建一个client上传文件, 取消上传并且释放这个client.   再次上传并且创建一个client. 报以下的warning, 

    A background URLSession with identifier com.aliyun.oss.backgroundsession already exists!

并且一直死锁在:

                BFTask * uploadPartTask = [self uploadPart:uploadPart];
            [uploadPartTask waitUntilFinished];

如果你们的client要设计成单例的, 要在文档中说明.

**Comment by com314159** [comment]
看一下这个, 应该是要单实例. 主要是一直卡在那里, 死锁.  如果是要单实例, 你们应该重新设计初始化的方法, 不然会有问题.   http://stackoverflow.com/questions/26453822/using-afnetworking-2-0-with-background-tasks

**Comment by xuyecan** [comment]
谢谢指出。

这个问题已经在[#4fb8a64](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/4fb8a648f4ce72889780b125c10a67c032b52048)中修复，如果需要创建多个允许后台上传的client实例，那么需要自行设置backgroundServiceIdentifier。

文档还没有更新上去，抱歉。

**Comment by xuyecan** [comment]
已经在 [#35fe715](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/35fe715beec92fa44298118d1d0d599e0fea1727)注明。此外，如果没有特殊的需求如不同的bucket endpoint设置，建议全局只使用一个OSSClient实例。
