### ISSUE TITLE
OSSReachability

### ISSUE THREAD

**Issue by SarahCarrie** [aliyun/aliyun-oss-ios-sdk#116]
Reachability.h: Unsupported: typedef changes linkage of anonymous type, but linkage was already computed
“enum NetworkStatus ”  -  It's very easy to repeat

**Comment by duan007a** [comment]
thanks for your feedback!we will fix it in the near future.

**Comment by SarahCarrie** [comment]
pod AliyunOSSiOS时，你们直接给Framework，也可以呀

**Comment by duan007a** [comment]
2.9.3已经做出更改，请更新到最新版使用
