### ISSUE TITLE
iOS 7 ResumableuploadFile  死锁

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#12]
一直卡在这里, 

            uploadPart.uploadPartData = [handle readDataOfLength:(NSUInteger)readLength];
            BFTask * uploadPartTask = [self uploadPart:uploadPart];
            [uploadPartTask waitUntilFinished];

经发现, 只要执行uploadPart有异常, 都会死锁在这里. 多个OSSClient实例也是一样的.  我觉得, 无论发生何异常, 都不应该死锁在这里. 这个异常, 在iOS 7上面可以重现

**Comment by com314159** [comment]
报的错是:  Data tasks are not supported in background sessions.
NSGenericException

**Comment by com314159** [comment]
死锁的原因是: 抛出了Exception , 但是没有error, 所以以下分支没有调用:

        if (task.error) {
            requestDelegate.completionHandler(nil, task.error);
        }
        return nil;

**Comment by com314159** [comment]
你们代码中还有很多判断task.error的地方, 这些地方你们审查一下,都是有问题的. 所有的地方, 应该判断
       
           if (task.error || task.isFaulted || task.isCancelled) {

            }

**Comment by xuyecan** [comment]
已修复，见 [#1833930](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/1833930f037663620346c1d447c1d7f5ec302819)。

问题是由backgroundsession在iOS7上的兼容性问题引起。解决方案是，开启后台session只对上传文件生效。

至于判断task.error的地方，设计之初就是尽可能规避exception，并且不使用BFTask的cancel机制，对用户只暴露是否error两个状态。这里网络层可能会抛出exception，已经加了判断并做转化。其他地方会再仔细review。

谢谢。
