### ISSUE TITLE
导入 SDK到我的工程后运行崩溃

### ISSUE THREAD

**Issue by Halokk** [aliyun/aliyun-oss-ios-sdk#122]
通过运行下载到的包内的sh文件获得的SDK包，导入到我的工程后，运行崩溃，然后准备添加依赖，但是依赖一直无法添加，在other link 里加了绝对路径访问也会运行崩溃

**Comment by 1019272778** [comment]
我们测试暂无发现问题。是否方便把你的工程配置发过来呢？另，如果着急使用，可以先尝试用引入源码的方式

**Comment by Halokk** [comment]
我的工程配置好像没什么其他，就一个other link 里设置了-Obj，其他的还有哪些地方需要设置或者查看的么

**Comment by 1019272778** [comment]
我们无法看到你的配置内容。在github中的demo是正常。你看看demo在您的电脑上是否是正常运行的呢？如果正常，可以和您自己配置对比看一下。

**Comment by Halokk** [comment]
示例代码直接就运行不了，
![image](https://user-images.githubusercontent.com/15354484/36060404-fc5f010e-0e83-11e8-83b9-2d320896f5a0.png)

**Comment by 1019272778** [comment]
我们联系了几个用户都没发现示例代码的问题。具体是什么错误呢？你可以对照一个可运行的工程对照看一下吗？

**Comment by Halokk** [comment]
<img width="543" alt="69133ea631773f84678aecb233c9a329" src="https://user-images.githubusercontent.com/15354484/36659685-37125f24-1b10-11e8-9db1-e33c78988b17.png">

**Comment by 1019272778** [comment]
@Halokk 可以参看如下配置
![config](https://user-images.githubusercontent.com/12809715/36709072-fded949c-1bb0-11e8-9f3e-19d051214b93.png)

**Comment by 1019272778** [comment]
您也可以咨询一下身边其他的ios 小伙伴。暂时没有反馈说范例工程无法使用的情况。

**Comment by Icelandre** [comment]
<img width="627" alt="2018-03-01 10 40 12" src="https://user-images.githubusercontent.com/11372239/36824412-2087e0b0-1d3d-11e8-942e-116ab2f69531.png">
下载的demo安装的时候出现这个问题

**Comment by 1019272778** [comment]
这个是找不到framework。请问您的开发环境是什么？这个跟sdk关系不大。应该是开发环境问题。要不你把你工程打包后发过来我们看一下是否可以运行。
