### ISSUE TITLE
initWithEndPoind 在多endpoint instance初始化场景时会崩溃！

### ISSUE THREAD

**Issue by wizardguy** [aliyun/aliyun-oss-ios-sdk#126]
* thread #22, queue = 'com.apple.root.default-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0xe5711bec8)
    frame #0: 0x00000001828dd7f4 libobjc.A.dylib`objc_object::release() + 16
  * frame #1: 0x0000000105ed9630 AliyunOSSiOS`-[OSSClient initWithEndpoint:credentialProvider:clientConfiguration:](self=0x00000001c4053020, _cmd="initWithEndpoint:credentialProvider:clientConfiguration:", endpoint=@"XXX", credentialProvider=XXX, conf=XXX) at OSSClient.m:46

使用场景是：App需要同时初始化多个bucket endpoint，所以遍历一个bucket参数数组多次调用initWithEndPoint。

目前已经收到接近几千份crash 报告，全部在这个位置crash，并且在真机测试时能够大概率重现。
追踪crash点是OSSClient.m的46行：
lock = [NSObject new]

lock是Class static 变量，可能的修改方案：
if (lock != nil) {
  lock = [NSObject new];
}

或者将lock设置为实例变量。

**Comment by wizardguy** [comment]
<img width="588" alt="2018-03-08 12 55 15" src="https://user-images.githubusercontent.com/13234873/37133793-5ccbce2c-22d0-11e8-93d9-d3368737c74f.png">
<img width="253" alt="2018-03-08 12 55 34" src="https://user-images.githubusercontent.com/13234873/37133797-5f8a2de8-22d0-11e8-9f86-e6f9652b76ca.png">

**Comment by 1019272778** [comment]
@wizardguy 感谢，问题已经修正。最新的master已经修复问题。近期也会发一个版本解决该问题。

**Comment by duan007a** [comment]
#127
