### ISSUE TITLE
是不是新的不支持模拟器了

### ISSUE THREAD

**Issue by hegelsu** [aliyun/aliyun-oss-ios-sdk#128]
原来./buildFramework.sh后framewrok大约有10M左右，现在的只有6M了，是不是不支持模拟器了？

**Comment by JohnTsaii** [comment]
lipo -info 我刚看了 是支持模拟器的

**Comment by hegelsu** [comment]
看了一下日志，这个要如何弄：
installApplication:withOptions:error:: Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedDescription=This app could not be installed at this time., NSUnderlyingError=0x7fedc5d29510 {Error Domain=MIInstallerErrorDomain Code=35 "Failed to load Info.plist from bundle at path /Users/suyx/Library/Developer/CoreSimulator/Devices/699DAD0F-D8FD-4823-AC62-42E63A0F088C/data/Library/Caches/com.apple.mobile.installd.staging/temp.fkmyqG/extracted/UCUXiOS.app/Frameworks/AliyunOSSiOS.framework" UserInfo={LegacyErrorString=PackageInspectionFailed, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=38, NSLocalizedDescription=Failed to load Info.plist from bundle at path /Users/suyx/Library/Developer/CoreSimulator/Devices/699DAD0F-D8FD-4823-AC62-42E63A0F088C/data/Library/Caches/com.apple.mobile.installd.staging/temp.fkmyqG/extracted/UCUXiOS.app/Frameworks/AliyunOSSiOS.framework}}}

**Comment by hegelsu** [comment]
上一次buildFramework之后直接可用的是版本73d519a

**Comment by hegelsu** [comment]
也就是这个版本73d519a编译的是10M，之后的就变成了6M了

**Comment by duan007a** [comment]
@hegelsu 多谢您的反馈，您可以选择release2.9.2版本使用，或者更新到master最新代码就可以避免这个问题了

**Comment by hegelsu** [comment]
可以了
