### ISSUE TITLE
请问ios 如何多任务上传文件。

### ISSUE THREAD

**Issue by XJ-Code** [aliyun/aliyun-oss-ios-sdk#132]
如题

**Comment by 1019272778** [comment]
这个功能可能是更偏业务。sdk只是提供对应api的移动端的封装。

**Comment by dd9913762113** [comment]
多任务上传好麻烦
果然 oss 考虑的不是用户
那要 oss  有毛线用
考虑安全的话，全部都由后端控制了
oss sdk  没啥用处了
