### ISSUE TITLE
在进度回调里发送通知，在通知中切换主线程更新UI，必须文件全部上传完了才一起更新UI

### ISSUE THREAD

**Issue by haihailaiye** [aliyun/aliyun-oss-ios-sdk#135]
swift4.0中，在进度回调里发送通知，在通知中切换主线程更新UI，在上传过程中通知全部卡死在进主线程的位子，然后上传完后，一起全部进入主线程回调。

**Comment by duan007a** [comment]
@haihailaiye 使用OSSClient返回的task时，不要在主线程调用task.waitUntilFinished()
