### ISSUE TITLE
更新版本后报错

### ISSUE THREAD

**Issue by huangping35** [aliyun/aliyun-oss-ios-sdk#136]
我把sdk更新到2.10后就报错，如果用回2.9.2就没有问题。报错如下：Attempted to create a task in a session that has been invalidated

 上传头像照片错误 Error Domain=com.aliyun.oss.clientError Code=9 "(null)" UserInfo={ErrorMessage=Catch exception - Task created 

这个要怎么修改？

**Comment by gupengno1** [comment]
遇到一样的问题 求解决

**Comment by yunxtk99139** [comment]
求解

**Comment by OctMon** [comment]
同问

**Comment by 1019272778** [comment]
@huangping35 @gupengno1 @yunxtk99139 @OctMon 能否帮忙留一些代码片段？我们测试暂无发现改问题。另，client的生命周期和应用的生命周期要保持一直。

**Comment by OctMon** [comment]
@property (nonatomic, strong) OSSClient *client;

改成全局的就好了 @1019272778  感谢

**Comment by huangping35** [comment]
@1019272778  留什么代码？

**Comment by 1019272778** [comment]
@huangping35 @gupengno1 @yunxtk99139 @OctMon  就是麻烦你能提供一个一定出错的的demo。发到1019272778@qq.com邮箱。我们看看具体什么问题。

**Comment by popor** [comment]
被坑了一下午,暂且切到2.8.1下面是ok的.

**Comment by duan007a** [comment]
@popor 可以提供一个能复现问题的示例代码吗，方便我们定位问题，尽早修复！

**Comment by OctMon** [comment]
@interface CommonTools()

@property (nonatomic, strong) OSSClient *client;

@end


@implementation CommonTools

guoanSingleton_implementation(CommonTools)

- (OSSClient *)client {
    id<OSSCredentialProvider> credential = [[OSSFederationCredentialProvider alloc] initWithFederationTokenGetter:^OSSFederationToken * {
        
        OSSTaskCompletionSource *tcs = [OSSTaskCompletionSource taskCompletionSource];
        [GuoanSession postWithUrlString:@"https://gasq-web-thirdparty.guoanshequ.wang/gasq-web-thirdparty/oss/getststoken" parameters:nil success:^(NSDictionary *json) {
            GuoanLog(@"%@", json);
            NSInteger resCode = [[json valueForKey:@"code"] integerValue];
            if (resCode == 0) {
                NSString *jsonStr = [[json valueForKey:@"data"] valueForKey:@"jsonStr"];
                [tcs setResult:[GuoanCommonTools decrypt:jsonStr key:kSecret]];
            }
        } failure:^(NSError *error) {
            GuoanLog(@"%@", error);
            [tcs setError:error];
        }];
        
        [tcs.task waitUntilFinished];
        if (tcs.task.error) {
            GuoanLog(@"get token error: %@", tcs.task.error);
            return nil;
        } else {
            NSData *jsonData = [tcs.task.result dataUsingEncoding:NSUTF8StringEncoding];
            
            NSDictionary *json = [NSJSONSerialization JSONObjectWithData:jsonData options:NSJSONReadingMutableContainers error:nil];
            NSDictionary *object = json;
            OSSFederationToken * token = [OSSFederationToken new];
            token.tAccessKey = object[@"accessKeyId"];
            token.tSecretKey = object[@"accessKeySecret"];
            token.tToken = object[@"securityToken"];
            token.expirationTimeInGMTFormat = object[@"expiration"];
            GuoanLog(@"get token: %@", token);
            return token;
        }
    }];
    
    return [[OSSClient alloc] initWithEndpoint:@"http://oss-cn-beijing.aliyuncs.com" credentialProvider:credential];
}

+ (NSString *)getObjectKey {
    NSDate *currentDate = [NSDate date];
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    
    formatter.dateFormat = @"yyyy/MM/dd";
    NSString *pathString = [formatter stringFromDate:currentDate];
    
    NSString *uuidString = [NSUUID UUID].UUIDString;
    NSString *objectKey = [NSString stringWithFormat:@"ios/%@/%@.jpg", pathString, uuidString];
    
    return objectKey;
}

+ (void)uploadImage:(UIImage *)image progress:(void(^)(int64_t bytesSent, int64_t totalBytesSent, int64_t totalBytesExpectedToSend)) uploadProgress completion:(void (^)(NSString *imageUrl, NSError *error))completionHandler {
    NSData *imageData = UIImageJPEGRepresentation(image, 0.2);
    OSSPutObjectRequest *put = [[OSSPutObjectRequest alloc] init];
    put.bucketName = @"gemini-wlcb";
    put.objectKey = [CommonTools getObjectKey];
    put.uploadingData = imageData;
    put.uploadProgress = uploadProgress;
    
    GuoanHUD *hud = [[GuoanHUD alloc] init];
    [hud show];
    OSSClient *client = [CommonTools sharedInstance].client;
    OSSTask *task = [client putObject:put];
    
    [task continueWithBlock:^id(OSSTask *task) {
        [hud hide];
        if (completionHandler) {
            completionHandler(put.objectKey, task.error);
        }
        if (!task.error) {
            GuoanLog(@"upload object success!");
        } else {
            GuoanShowAlert(task.error.localizedDescription, [UIApplication sharedApplication].keyWindow.rootViewController);
            GuoanLog(@"upload object failed, error: %@", task.error);
        }
        return nil;
    }];
}

@end

**Comment by popor** [comment]
@duan007a 邮件已发送

**Comment by popor** [comment]
我的问题,只要不是局部变量就ok了

**Comment by huangping35** [comment]
//
//  AliYunToken.m
//  AnyDoor
//
//  Created by fry on 2017/7/11.
//  Copyright © 2017年 AnyDoor. All rights reserved.
//

#import "AliYunToken.h"
#import <AliyunOSSiOS/OSSService.h>

@implementation AliYunToken

+ (AliYunToken *)shareInstance
{
    static AliYunToken * token = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        token = [[self alloc] init];
    });
    return token;
}

- (void)aliyunUploadImage:(AliYunImageModel *)imageModel progress:(AliYunProgressBlock)ossprogress success:(AliYunSuccessBlock)osssuccess failure:(AliYunFailureBlock)ossfailure
{
    
    id<OSSCredentialProvider> credential =  [[OSSFederationCredentialProvider alloc] initWithFederationTokenGetter:^OSSFederationToken * {
        NSURL * url = [NSURL URLWithString:[NSString stringWithFormat:@"%@%@?ak=%@",ADURLBase,ADURLGetOSSStsToken,[ADUser sharedUser].ak]];
        NSURLRequest * request = [NSURLRequest requestWithURL:url];
        OSSTaskCompletionSource * tcs = [OSSTaskCompletionSource taskCompletionSource];
        NSURLSession * session = [NSURLSession sharedSession];
        
        
        NSURLSessionTask * sessionTask = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
            
            if (error)
            {
                [tcs setError:error];
                return;
            }
            
            [tcs setResult:data];
            
        }];
        
        [sessionTask resume];
        [tcs.task waitUntilFinished];
        
        if (tcs.task.error)
        {
            return nil;
        } else {
            NSDictionary * object = [NSJSONSerialization JSONObjectWithData:tcs.task.result options:kNilOptions error:nil];
            OSSFederationToken * token = [OSSFederationToken new];
            NSDictionary * tokenDic = object[@"data"];
            // 四个值缺一不可
            token.tAccessKey = [tokenDic objectForKey:@"AccessKeyId"];
            token.tSecretKey = [tokenDic objectForKey:@"AccessKeySecret"];
            token.tToken = [tokenDic objectForKey:@"SecurityToken"];
            token.expirationTimeInGMTFormat = [tokenDic objectForKey:@"Expiration"];
            OSSLogDebug(@"token: %@ %@ %@ %@", token.tAccessKey, token.tSecretKey, token.tToken, [object objectForKey:@"Expiration"]);
            return token;
        }
    }];
    
    OSSClientConfiguration * conf = [OSSClientConfiguration new];
    conf.maxRetryCount = 2;
    conf.timeoutIntervalForRequest = 30;
    conf.timeoutIntervalForResource = 24 * 60 * 60;
    
    OSSClient* client = [[OSSClient alloc] initWithEndpoint:kAliYunEndPoint  credentialProvider:credential clientConfiguration:conf];
    
    
    OSSPutObjectRequest * put = [OSSPutObjectRequest new];
    put.bucketName = kALiYunBucketName;
    
    put.objectKey = [NSString stringWithFormat:@"%@%@%@",imageModel.pathUrl,imageModel.fileName,imageModel.fileType];
    
    put.uploadingData = imageModel.data;
    
    put.uploadProgress = ^(int64_t bytesSent, int64_t totalByteSent, int64_t totalBytesExpectedToSend) {
        DLog(@"%lld, %lld, %lld", bytesSent, totalByteSent, totalBytesExpectedToSend);
        
        if (ossprogress)
        {
            ossprogress(@((totalByteSent*1.0)/totalBytesExpectedToSend));
        }
        
    };
    
    OSSTask* putTask  = [client putObject:put];
    
    //    [putTask waitUntilFinished]; // 阻塞直到上传完成
    //
    //    if (!putTask.error) {
    //        NSLog(@"upload object success!");
    //    } else {
    //        NSLog(@"upload object failed, error: %@" , putTask.error);
    //    }
    
    [putTask continueWithBlock:^id(OSSTask *task) {
        if (!task.error) {
            osssuccess(put.objectKey);
//            osssuccess([NSString stringWithFormat:@"http://%@.%@/%@",put.bucketName,endpoint,put.objectKey]);
            
        } else {
            
            ossfailure(task.error);
            
            //DLog(@"upload object failed, error: %@" , task.error);
        }
        return nil;
    }];
    
    
}



- (NSString *)aliyunSyncUploadImage:(AliYunImageModel *)imageModel
{
    id<OSSCredentialProvider> credential =  [[OSSFederationCredentialProvider alloc] initWithFederationTokenGetter:^OSSFederationToken * {
        NSURL * url = [NSURL URLWithString:[NSString stringWithFormat:@"%@%@?ak=%@",ADURLBase,ADURLGetOSSStsToken,[ADUser sharedUser].ak]];
        NSURLRequest * request = [NSURLRequest requestWithURL:url];
        OSSTaskCompletionSource * tcs = [OSSTaskCompletionSource taskCompletionSource];
        NSURLSession * session = [NSURLSession sharedSession];
        
        
        NSURLSessionTask * sessionTask = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
            
            if (error)
            {
                [tcs setError:error];
                return;
            }
            
            [tcs setResult:data];
            
        }];
        
        [sessionTask resume];
        [tcs.task waitUntilFinished];
        
        if (tcs.task.error)
        {
            return nil;
        } else {
            NSDictionary * object = [NSJSONSerialization JSONObjectWithData:tcs.task.result options:kNilOptions error:nil];
            OSSFederationToken * token = [OSSFederationToken new];
            NSDictionary * tokenDic = object[@"data"];
            // 四个值缺一不可
            token.tAccessKey = [tokenDic objectForKey:@"AccessKeyId"];
            token.tSecretKey = [tokenDic objectForKey:@"AccessKeySecret"];
            token.tToken = [tokenDic objectForKey:@"SecurityToken"];
            token.expirationTimeInGMTFormat = [tokenDic objectForKey:@"Expiration"];
            OSSLogDebug(@"token: %@ %@ %@ %@", token.tAccessKey, token.tSecretKey, token.tToken, [object objectForKey:@"Expiration"]);
            return token;
        }
    }];
    
    OSSClientConfiguration * conf = [OSSClientConfiguration new];
    conf.maxRetryCount = 2;
    conf.timeoutIntervalForRequest = 30;
    conf.timeoutIntervalForResource = 24 * 60 * 60;
    
    OSSClient* client = [[OSSClient alloc] initWithEndpoint:kAliYunEndPoint  credentialProvider:credential clientConfiguration:conf];
    
    
    OSSPutObjectRequest * put = [OSSPutObjectRequest new];
    put.bucketName = kALiYunBucketName;
    
    put.objectKey = [NSString stringWithFormat:@"%@%@%@",imageModel.pathUrl,imageModel.fileName,imageModel.fileType];
    
    put.uploadingData = imageModel.data;
    
    
    OSSTask* putTask  = [client putObject:put];
    
    [putTask waitUntilFinished]; // 阻塞直到上传完成

    if (!putTask.error)
    {
        NSLog(@"upload object success!");
        
        return put.objectKey;
        
    } else {
        
        NSLog(@"upload object failed, error: %@" , putTask.error);
        
    }
    
    return nil;
    
}
    
@end

**Comment by huangping35** [comment]
endpoint 这个只有一个而已 @1019272778 @duan007a

**Comment by duan007a** [comment]
@huangping35 让你的单例持有一个OSSClient实例，不要每次请求都去创建。链接是官方文档

**Comment by huangping35** [comment]
@popor @duan007a  完全正确，我把版本升级到最新的2.10.，把局部变量变为全局变量，整个app只有一个，就ok了，谢谢！

**Comment by chiefky** [comment]
> @huangping35 让你的单例持有一个OSSClient实例，不要每次请求都去创建。链接是官方文档

你好，请教个问题，刚开始用OSS 不知道错误处在哪，能帮忙看一下吗？ ERROR：AccessDenied 。看官方文档说是未授权，但是找过相关人员之后说是一定授权了，现在无从下手。希望收到一些建议。谢谢了。
2019-01-09 20:43:32.653134+0800 YXPSeller-iPhone[1637:190030] [Verbose]: did receive response: <NSHTTPURLResponse: 0x282476380> { URL: http://ali-ershouche-app.xin.com/oss-ios-demo-big-file?uploads } { Status Code: 403, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    Connection =     (
        "keep-alive"
    );
    "Content-Length" =     (
        257
    );
    "Content-Type" =     (
        "application/xml"
    );
    Date =     (
        "Wed, 09 Jan 2019 12:43:32 GMT"
    );
    EagleId =     (
        2a51041615470378124956502e
    );
    Server =     (
        Tengine
    );
    "Timing-Allow-Origin" =     (
        "*"
    );
    Via =     (
        "cache3.l2eu95-1[95,0], kunlun2.cn249[141,0]"
    );
    "x-oss-request-id" =     (
        5C35EC748ED5091138DF58BB
    );
    "x-oss-server-time" =     (
        9
    );
} }
2019-01-09 20:43:32.664502+0800 YXPSeller-iPhone[1637:190078] [Error]: http error response: <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>You have no right to access this object.</Message>
  <RequestId>5C35EC748ED5091138DF58BB</RequestId>
  <HostId>ershouche-app.oss-cn-beijing.aliyuncs.com</HostId>
</Error>
2019-01-09 20:43:32.680233+0800 YXPSeller-iPhone[1637:189691] dictionaryWithParser YES
2019-01-09 20:43:32.681207+0800 YXPSeller-iPhone[1637:190078] [Verbose]: current retry count: 0, retry type: 2
2019-01-09 20:43:32.681600+0800 YXPSeller-iPhone[1637:189488] faild ====
2019-01-09 20:43:33.734656+0800 YXPSeller-iPhone[1637:189488] System is no longer under (non-critical) memory pressure.
2019-01-09 20:43:42.932045+0800 YXPSeller-iPhone[1637:190031] TIC Read Status [5:0x28112e700]: 1:57
2019-01-09 20:44:43.002218+0800 YXPSeller-iPhone[1637:189693] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C4.1:2][0x149e56270] get output frames failed, state 8196
2019-01-09 20:44:43.003811+0800 YXPSeller-iPhone[1637:189693] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C4.1:2][0x149e56270] get output frames failed, state 8196
2019-01-09 20:44:43.006240+0800 YXPSeller-iPhone[1637:189693] TIC Read Status [4:0x0]: 1:57
2019-01-09 20:44:43.006387+0800 YXPSeller-iPhone[1637:189693] TIC Read Status [4:0x0]: 1:57
