### ISSUE TITLE
Carthage build出来的是OSX的版本，没有iOS版本

### ISSUE THREAD

**Issue by gaoshanyu** [aliyun/aliyun-oss-ios-sdk#137]
Carthage version： 0.29.0
Carthage code：
`github "aliyun/aliyun-oss-ios-sdk"`
Build截图：
<img width="479" alt="screen shot 2018-04-02 at 11 39 16 am" src="https://user-images.githubusercontent.com/10546774/38182257-d58081ac-366a-11e8-8cb8-e822cf64b34e.png">

**Comment by 1019272778** [comment]
sdk 目前只支持cocoapods。Carthage 暂时没有计划
