### ISSUE TITLE
IOS 2.0.2 上传文件问题？

### ISSUE THREAD

**Issue by lubaoyilang** [aliyun/aliyun-oss-ios-sdk#14]
上传文件 回调中  没有 文件在云端的 URL 嘛？？

需要自己进行拼接对吗？

但是我看到 开启log日志后，你们打印出好多次文件云端的URL

你们的OSS 在设计上就是要用户 在上传成功的 回调中 自己拼接URL   
而不是你们返回 这个URL ，对吗？

**Comment by xuyecan** [comment]
签名文件的URL是一个独立功能，提供的接口是：
