### ISSUE TITLE
OssTask 在Swift 中无法使用

### ISSUE THREAD

**Issue by JonHome** [aliyun/aliyun-oss-ios-sdk#148]
continue 是关键字 
ossTask.continue 的使用会弹出错误警告，为什么这个问题持续了很久没人在乎的？

**Comment by haihailaiye** [comment]
swift demo在哪，官网链接的demo全是oc的

**Comment by duan007a** [comment]
@haihailaiye 下载工程代码，工程里面有OSSSwiftDemo的使用示例
