### ISSUE TITLE
Attempted to create a task in a session that has been invalidated

### ISSUE THREAD

**Issue by 12207480** [aliyun/aliyun-oss-ios-sdk#149]
我在上传图片的时候在项目中的出错，但是 这个demo里没有问题
错误信息
Printing description of task->_error:
Error Domain=com.aliyun.oss.clientError Code=9 "(null)" UserInfo={ErrorMessage=Catch exception - Task created in a session that has been invalidated}

**Comment by 1019272778** [comment]
请问你是怎么创建以及使用ossClient？ossClient的生命周期需要和app的生命周期一致。

**Comment by jerny0** [comment]
可能是 ossClient 被销毁了

**Comment by 12207480** [comment]
我换回2.9.2版本 就没问题

**Comment by zhyKing** [comment]
ossClient 被销毁了，ossClient 不能是局部变量，可以把 ossClient设置为当前类的属性

**Comment by duan007a** [comment]
@12207480 请保持OSSClient的实例和App的生命周期一致
