### ISSUE TITLE
OSS上传图片时怎么使用Background Transfer Service？

### ISSUE THREAD

**Issue by liuyunclouder** [aliyun/aliyun-oss-ios-sdk#15]
这是我目前的设置
初始化client：

        OSSClientConfiguration *conf = [OSSClientConfiguration new];
        conf.enableBackgroundTransmitService = YES;
        
        _backgroundTransferClient = [[OSSClient alloc] initWithEndpoint:endpoint credentialProvider:credential clientConfiguration:conf];

设置回调：

        - (void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)())completionHandler
        {

            [[[EZOAliyunOSSManager sharedInstance] backgroundTransferClient] setBackgroundSessionCompletionHandler:completionHandler];
            NSLog(@"completionHandler called");

        }

开始上传：

        OSSClient *client = [[EZOAliyunOSSManager sharedInstance] backgroundTransferClient];
        BFTask * putTask = [client putObject:put];

但我上传后发现你们的OSSNetworking.m中的URLSessionDidFinishEventsForBackgroundURLSession始终没有被调用，麻烦解答一下，多谢

**Comment by xuyecan** [comment]
当前版本暂时不支持这个功能，在一些机型上，发现NSURLSession的后台传输开启后，设置的超时时间不生效，在网络无响应时，请求永远不会进入失败回调。

所以请暂时不要开启这个选项。

**Comment by liuyunclouder** [comment]
好的，多谢

**Comment by gaoshanyu** [comment]
现在支持了吗？
