### ISSUE TITLE
版本2.9.2 一直报crash

### ISSUE THREAD

**Issue by SnoopPanda** [aliyun/aliyun-oss-ios-sdk#153]
-[NSPathStore2 endpoint]: unrecognized selector sent to instance 0x11e4c4000
-[NSConcreteMutableData endpoint]: unrecognized selector sent to instance 0x1c425a820
-[__NSCFString endpoint]: unrecognized selector sent to instance 0x1c5051040
-[NSPathStore2 invokeRequest:requireAuthentication:]: unrecognized selector sent to instance 0x1c3c4ca20

大概都是因为这个[OSSClient completeMultipartUpload:]，以前似乎没这个问题，我找不到问题处在哪里，能帮助我吗？

**Comment by duan007a** [comment]
请保持你的OSSclient和App的周期保持一致。
