### ISSUE TITLE
无法pod

### ISSUE THREAD

**Issue by 76ge** [aliyun/aliyun-oss-ios-sdk#154]
Installing AliyunOSSiOS (2.10.0)

[!] Error installing AliyunOSSiOS
[!] /usr/local/bin/git clone https://github.com/aliyun/aliyun-oss-ios-sdk.git /var/folders/q9/040thvzn7nn3r6q8q76fwqh00000gn/T/d20180622-36820-1hx6dfp --template= --single-branch --depth 1 --branch release_2.10.0

Cloning into '/var/folders/q9/040thvzn7nn3r6q8q76fwqh00000gn/T/d20180622-36820-1hx6dfp'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by duan007a** [comment]
@76ge 请尝试pod拉取最新版本2.10.4

**Comment by alex0811** [comment]
最新版本2.10.4也拉取失败

**Comment by gaimanjing** [comment]
同问

**Comment by vincentwu08** [comment]
最新版本2.10.4拉取失败，Gighub也Clone不下来

**Comment by alex0811** [comment]
@vincentwu08 问题解决了，终端翻墙即可

**Comment by vincentwu08** [comment]
@alex0811 现在不FQ也可以了 😆

**Comment by liwangwang123** [comment]
翻墙也不行,每次都很难下载,

**Comment by MinSZCIOS** [comment]
git config --global --unset http.proxy 
git config --global --unset https.proxy

**Comment by jiangxiaopeng** [comment]
> git config --global --unset http.proxy git config --global --unset https.proxy

还得是你啊，bro
