### ISSUE TITLE
upload object failed, error: Error Domain=com.aliyun.oss.clientError Code=5 "已取消" 

### ISSUE THREAD

**Issue by Heisenbean** [aliyun/aliyun-oss-ios-sdk#155]
for循环上传多张图片的时候报这个错误,单独上传一张照片没问题

**Comment by JFwen** [comment]
请教一下，这个问题怎么解决的，我也出现上传多张图片的时候被cancel了，关键是我在单利里面持有了client

**Comment by JFwen** [comment]
> for循环上传多张图片的时候报这个错误,单独上传一张照片没问题
请教一下，这个问题怎么解决的，我也出现上传多张图片的时候被cancel了，关键是我在单利里面持有了client
