### ISSUE TITLE
应用 第一次使用 oss 上传出现错误 Error Domain=com.aliyun.oss.clientError Code=6 "The certificate for this server is invalid

### ISSUE THREAD

**Issue by manajay** [aliyun/aliyun-oss-ios-sdk#156]
Error Domain=com.aliyun.oss.clientError Code=6 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “59.110.185.67” which could put your confidential information at risk." UserInfo={NSErrorFailingURLKey=https://59.110.185.67/08B93B7578D711E7855190E2BACDCE28/note/ABBDAE82-D39F-4928-A41D-4E05EA490124.wav, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, OriginErrorCode=-1202, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “59.110.185.67” which could put your confidential information at risk., NSErrorFailingURLStringKey=https://59.110.185.67/08B93B7578D711E7855190E2BACDCE28/note/ABBDAE82-D39F-4928-A41D-4E05EA490124.wav, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843}

**Comment by duan007a** [comment]
请将endpoint切换到http访问。或者设置OSSClientConfiguration中的isHttpdnsEnable为NO。sdk不支持在https下进行ip直连的服务

**Comment by duan007a** [comment]
因为SNI（单IP多HTTPS证书）场景下，iOS上层网络库NSURLSession没有提供接口进行SNI字段的配置,所以SDK不会考虑支持。
