### ISSUE TITLE
ios7上传的时候会崩溃，因为sdk使用了containsString：方法

### ISSUE THREAD

**Issue by jlideasoft** [aliyun/aliyun-oss-ios-sdk#16]
__NSCFString containsString:]: unrecognized selector sent to instance 0x7f876b79e160

**Comment by xuyecan** [comment]
已修复。commit [#a1e9](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/a1e95eee6197dad71364718f295f4f8473264e81)。
