### ISSUE TITLE
iOS上传失败，少写了这句代码，让我加班，坑了我了

### ISSUE THREAD

**Issue by Laughing1206** [aliyun/aliyun-oss-ios-sdk#161]
id<OSSCredentialProvider> credential = [[OSSStsTokenCredentialProvider alloc] initWithAccessKeyId:token.AccessKeyId secretKeyId:token.AccessKeySecret securityToken:token.SecurityToken];
            
            OSSClient * client = [[OSSClient alloc] initWithEndpoint:token.endpoint credentialProvider:credential];
            
            //任务执行
            OSSPutObjectRequest * put = [OSSPutObjectRequest new];
            put.bucketName = token.bucket;
            NSString *objectKeys = [NSString stringWithFormat:@"%@.jpg",[[NSDate date] timestamp]];
            put.objectKey = objectKeys;
            put.uploadingData = UIImageJPEGRepresentation(image, 1);
            put.contentType = @"image/jpeg";
            
            OSSTask * putTask = [client putObject:put];
            
            [putTask continueWithBlock:^id(OSSTask * task) {
                task = [client presignPublicURLWithBucketName:token.bucket
                                                withObjectKey:objectKeys];//少些这句
                if (!task.error)
                {
                    complete(task.result);
                }
                else
                {
                    complete(nil);
                }
                return nil;
            }];

**Comment by Quanhua-Guan** [comment]
这么写貌似不对, 这里```task = [client presignPublicURLWithBucketName:token.bucket
                                            withObjectKey:objectKeys];```执行以后, task.error 肯定为 nil, 不管之前 task.error 是否为 nil. 而且, 如果要执行presignPublicURLWithBucketName的话, 也应该在上传任务执行前执行.
