### ISSUE TITLE
Multi crash

### ISSUE THREAD

**Issue by suweiz19890921** [aliyun/aliyun-oss-ios-sdk#162]
有时候多文件上传Crash
￼
![pasted graphic 1](https://user-images.githubusercontent.com/17306517/43111097-178dffa6-8f22-11e8-8e3b-af178a7d26e7.png)
![pasted graphic 2](https://user-images.githubusercontent.com/17306517/43111098-17c13a92-8f22-11e8-8553-0ce04999808c.png)

**Comment by duan007a** [comment]
这个是由于接入方代码没有持有ossclient的实例，导致ossclient提前释放了。
