### ISSUE TITLE
./build/Release-iphoneos/AliyunOSSiOS.framework: No such file or directory fatal error

### ISSUE THREAD

**Issue by loss99** [aliyun/aliyun-oss-ios-sdk#166]
Xcode 9.41
mac 环境 10.14 Beta (18A336e)
终端
执行  sh ./buildFramework.sh 后
得到 ====>
    /usr/bin/codesign --force --sign - --timestamp=none /Users/jiahailiang\ 1/Desktop/aliyun-oss-ios-sdk/build/Release-iphonesimulator/AliyunOSSiOS.framework

Touch /Users/jiahailiang\ 1/Desktop/aliyun-oss-ios-sdk/build/Release-iphonesimulator/AliyunOSSiOS.framework (in target: AliyunOSSSDK iOS)
    cd /Users/jiahailiang\ 1/Desktop/aliyun-oss-ios-sdk
    /usr/bin/touch -c /Users/jiahailiang\ 1/Desktop/aliyun-oss-ios-sdk/build/Release-iphonesimulator/AliyunOSSiOS.framework

** BUILD SUCCEEDED **

cp: ./build/Release-iphoneos/AliyunOSSiOS.framework: No such file or directory
fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: ./build/Release-iphoneos/AliyunOSSiOS.framework/AliyunOSSiOS (No such file or directory)
➜  aliyun-oss-ios-sdk git:(master) ✗ sh ./buildFramework.sh

**Comment by duan007a** [comment]
@loss99 这个应该跟你的系统环境有关系，建议你更新到正式版的mac环境重试。
