### ISSUE TITLE
下载的方法会卡主线程吗？

### ISSUE THREAD

**Issue by qiangzai** [aliyun/aliyun-oss-ios-sdk#172]
OSSGetObjectRequest * request = [OSSGetObjectRequest new];
    // 必填字段
    request.bucketName = @"<bucketName>";
    request.objectKey = @"<objectKey>";
    // 可选字段
    request.downloadProgress = ^(int64_t bytesWritten, int64_t totalBytesWritten, int64_t totalBytesExpectedToWrite) {
        // 当前下载段长度、当前已经下载总长度、一共需要下载的总长度
        NSLog(@"%lld, %lld, %lld", bytesWritten, totalBytesWritten, totalBytesExpectedToWrite);
        float value = totalBytesWritten * 1.0f / totalBytesExpectedToWrite;
        NSLog(@"value = %f",value);
    };
    [self.client getObject:request];
    [task continueWithBlock:^id _Nullable(OSSTask * _Nonnull task) {
        if (!task.error) {
            NSLog(@"download object success!");
            OSSGetObjectResult *getResult = task.result;
            NSLog(@"download result = %@",getResult.objectMeta);
            self.b = YES;
        } else {
            NSLog(@"download object failed, error = %@",task.error);
            self.b = NO;
        }
    }];

发现下载时，不能点击页面上的其他按钮，是否把这段代码放在异步线程里也会卡主线程？

**Comment by duan007a** [comment]
你好，这种写法也不会阻塞当前线程的，只有在调用[task waitUntilFinished]才会阻塞当前线程


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
