### ISSUE TITLE
demo上传图片有问题

### ISSUE THREAD

**Issue by errorUserInfo** [aliyun/aliyun-oss-ios-sdk#174]
Could not successfully update network info during initialization

**Comment by errorUserInfo** [comment]
Break on warnBlockingOperationOnMainThread() to debug

**Comment by errorUserInfo** [comment]
Warning: A long-running operation is being executed on the main thread

**Comment by 1019272778** [comment]
请问是在初始化时更新什么网络信息呢？

**Comment by duan007a** [comment]
1.模拟器运行时没有运营商信息，会打印相关log。2.主线程执行耗时任务时会给出警告⚠️信息。  我这边优化一下涉及到的代码
