### ISSUE TITLE
cocopods集成后OSSNetworking.h报错

### ISSUE THREAD

**Issue by ui03** [aliyun/aliyun-oss-ios-sdk#176]
￼
![wechatimg21860](https://user-images.githubusercontent.com/17630008/45797110-706cc580-bcd6-11e8-9b8e-fe155ccb4616.jpeg)

**Comment by duan007a** [comment]
请检查一下你工程中的设置,如果还有问题请将您遇到的详细问题贴一下，我们这边验证是没有问题的。另外提醒一下cocoapods上面最新的版本是2.10.7

**Comment by ui03** [comment]
![wechatimg21989](https://user-images.githubusercontent.com/17630008/45869738-cbc4b380-bdbb-11e8-8b69-e4ac476ab09e.jpeg)
![wechatimg21990](https://user-images.githubusercontent.com/17630008/45869739-cbc4b380-bdbb-11e8-9944-21eddcb94b8c.jpeg)
![wechatimg21991](https://user-images.githubusercontent.com/17630008/45869740-cc5d4a00-bdbb-11e8-87f7-da96cce79992.jpeg)
![wechatimg21994](https://user-images.githubusercontent.com/17630008/45869741-cc5d4a00-bdbb-11e8-9790-9ec64318411d.jpeg)
刚更新了2.10.7

**Comment by ui03** [comment]
@duan007a 引用#import <AliyunOSSiOS/OSSService.h>后运行报错

**Comment by ui03** [comment]
![wechatimg22055](https://user-images.githubusercontent.com/17630008/45948705-a5a54a80-c02b-11e8-9c44-22bd016b8066.jpeg)
@duan007a 麻烦帮忙看下、是和哪个库有冲突吗？因为我这边单独集成阿里云没问题、但是加上这些库、就报错了
