### ISSUE TITLE
请问如何指定上传后的文件后缀?

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#18]
我现在认为objectKey就是文件名, 所以直接在objectKey里面加的后缀, 请问一下正确的解决方法是怎样的呢?

**Comment by xuyecan** [comment]
请问你是指文件后缀，还是文件类型？

如果是文件后缀，那么一起写到objectKey里就好了。比如上传一张图片，objectKey为"image.jpeg"，那么上传后文件名保持不变，后缀就是".jpeg"。

如果是文件类型，那么，上传构造 putObjectRequest 时，可以直接设置 putObjectRequest.contentType = "image/jpeg"。

**Comment by com314159** [comment]
是指文件名的后缀, 嗯, 我现在就是拼接到objectKey后面的
