### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by ioschen** [aliyun/aliyun-oss-ios-sdk#190]
![image](https://user-images.githubusercontent.com/5210832/48814863-6bc89a00-ed77-11e8-8d45-dfc70c393166.png)
警告太多

**Comment by duan007a** [comment]
考虑到兼容性有些deprecated warning还不能移除，不过已经在计划中，后面在大版本升级时会完全改掉，感谢您的反馈

**Comment by ioschen** [comment]
When on earth can I stop waiting?
