### ISSUE TITLE
小白求助Archive时候framework报错的问题

### ISSUE THREAD

**Issue by 18Yi** [aliyun/aliyun-oss-ios-sdk#193]
SDK debug模式下可以运行  但是archive的时候报错了：

ld: bitcode bundle could not be generated because '/..../AliyunOSSiOS.framework/AliyunOSSiOS(OSSNetworkingRequestDelegate.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/..../AliyunOSSiOS.framework/AliyunOSSiOS' for architecture armv7

我看文档里有说明 但是我不知道应该怎么生成archive时候的framework
如果用这个项目里边的文件archive export出来是空的   所以不知道怎么生成正式的framework

本人小白...

**Comment by weifans** [comment]
@18Yi 为什么关闭了，解决了吗

**Comment by iamjia** [comment]
我也遇到了相同的问题

**Comment by oobabe** [comment]
![8A0C9812-C73E-42C8-ABE8-A98AD6A392F8](https://user-images.githubusercontent.com/17685601/126634138-ab86559d-807c-451b-9dfd-844a4278f9fc.JPEG)

Build Settings - Enable Bitcode - No

提示: 如果找不到"Enable Bitcode"就搜索一下Bitcode
Tip: If you cannot find "Enable Bitcode", search Bitcode
