### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by iOSXH** [aliyun/aliyun-oss-ios-sdk#199]
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 9121, TID: 3570140, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   video                               0x0000000104dfe8f4 -[UTSelfStaticsManager getAppState] + 60
5   video                               0x0000000104dfe7f0 -[UTSelfStaticsManager onEventForCrash] + 256
6   video                               0x0000000104ddd67c __40-[UTMCSystemHook appDIdEnterBackground:]_block_invoke.51 + 196
7   libdispatch.dylib                   0x0000000105b02c28 _dispatch_call_block_and_release + 32
8   libdispatch.dylib                   0x0000000105b041c0 _dispatch_client_callout + 20
9   libdispatch.dylib                   0x0000000105b07158 _dispatch_queue_override_invoke + 908
10  libdispatch.dylib                   0x0000000105b15210 _dispatch_root_queue_drain + 356
11  libdispatch.dylib                   0x0000000105b15be4 _dispatch_worker_thread2 + 144
12  libsystem_pthread.dylib             0x00000001eab6cbc0 _pthread_wqthread + 476
13  libsystem_pthread.dylib             0x00000001eab72dd4 start_wqthread + 4
2019-04-10 18:41:35.100312+0800 video[9121:3570140] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 9121, TID: 3570140, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   video                               0x0000000104dfe8f4 -[UTSelfStaticsManager getAppState] + 60
5   video                               0x0000000104dfe7f0 -[UTSelfStaticsManager onEventForCrash] + 256
6   video                               0x0000000104ddd67c __40-[UTMCSystemHook appDIdEnterBackground:]_block_invoke.51 + 196
7   libdispatch.dylib                   0x0000000105b02c28 _dispatch_call_block_and_release + 32
8   libdispatch.dylib                   0x0000000105b041c0 _dispatch_client_callout + 20
9   libdispatch.dylib                   0x0000000105b07158 _dispatch_queue_override_invoke + 908
10  libdispatch.dylib                   0x0000000105b15210 _dispatch_root_queue_drain + 356
11  libdispatch.dylib                   0x0000000105b15be4 _dispatch_worker_thread2 + 144
12  libsystem_pthread.dylib             0x00000001eab6cbc0 _pthread_wqthread + 476
13  libsystem_pthread.dylib             0x00000001eab72dd4 start_wqthread + 4

**Comment by Thomaszhouwu** [comment]
你好，我也发现类似问题，请问如何解决？

**Comment by Huaida** [comment]
同问，请问如何解决？

**Comment by luchaoqun123** [comment]
问题为啥直接被关闭了
