### ISSUE TITLE
有时候任务调用cancel无法取消

### ISSUE THREAD

**Issue by xuyecan** [aliyun/aliyun-oss-ios-sdk#21]
检查了networking.m文件，可能问题发生在：调用cancel时，如果sessionTask还未建立，则不执行任何动作。考虑到，sessionTask建立前，获取sts token可能存在网络交互，导致较长耗时，这个过程中cancel的概率是有一定概率的，不能忽略这种情况。

所以，应该在requestdelegate中加入cancelled标志，建立sessionTask前判断下如果已经取消，就放弃任务。

**Comment by SducodeMonkey** [comment]
修改后提了MR。
