### ISSUE TITLE
oss crash

### ISSUE THREAD

**Issue by YWD** [aliyun/aliyun-oss-ios-sdk#215]
最近发现OSS崩溃比较频繁希望开发人员能够帮助解决问题。
![image](https://user-images.githubusercontent.com/8605395/61689183-4acaa580-ad59-11e9-9f00-82681093a30d.png)
![image](https://user-images.githubusercontent.com/8605395/61689238-67ff7400-ad59-11e9-88a1-f690cfba7f3a.png)
基本上就是这两个错误。
我不懂oc，如果还需要提供哪些信息请告知以便解决问题。

**Comment by sdlcdhc** [comment]
这两个异常跟此 sdk 没有关系的，第一个 CODESIGNING 的错误是 app 签名报错，第二个问题的ASSERTIOND,Code 0x8badf00d是 iOS系统的 watchdog 超时引起的，可参考苹果官方文档 https://developer.apple.com/library/archive/technotes/tn2151/_index.html#//apple_ref/doc/uid/DTS40008184-CH1-EXCEPTION_INFO

**Comment by YWD** [comment]
每次崩溃都是发生在图片上传的时候。我先看下文档。

**Comment by YWD** [comment]
https://github.com/Instabug/Instabug-iOS/issues/305，你好，可以看下这个问题吗，我的错误看着和这个很像，是后台任务的问题吗？

**Comment by sdlcdhc** [comment]
@YWD  请提供一下完整的崩溃堆栈信息，另外提供一个可以复现此问题的示例工程，这些东西对排查此问题应该是很有帮助的

**Comment by YWD** [comment]
感谢回复，我升级了flutter版本，这个问题目前没有发生，我先close issue，后续有问题再来反馈。
