### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mcheng315** [aliyun/aliyun-oss-ios-sdk#221]
检测到有崩溃

Fatal Exception: NSInvalidArgumentExceptiondata parameter is nil Raw Text
--
0 | CoreFoundation | (Missing)
1 | libobjc.A.dylib | objc_exception_throw
2 | CoreFoundation | (Missing)
3 | Foundation | (Missing)
4 | Mandian | OSSHttpdns.m line 112__26-[OSSHttpdns resolveHost:]_block_invoke + 112
5 | CFNetwork | __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke
6 | CFNetwork | __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke
7 | Foundation | (Missing)
8 | Foundation | (Missing)
9 | Foundation | (Missing)
10 | Foundation | (Missing)
11 | libdispatch.dylib | _dispatch_call_block_and_release
12 | libdispatch.dylib | _dispatch_client_callout
13 | libdispatch.dylib | _dispatch_continuation_pop$VARIANT$mp
14 | libdispatch.dylib | _dispatch_async_redirect_invoke
15 | libdispatch.dylib | _dispatch_root_queue_drain
16 | libdispatch.dylib | _dispatch_worker_thread2
17 | libsystem_pthread.dylib | _pthread_wqthread
18 | libsystem_pthread.dylib | start_wqthread

**Comment by pushuhengyang** [comment]
> 各个系统版本都有崩溃，占比如下
> iOS12 68%
> iOS13 20%
> iOS11 9%
> iOS10 2%

这个错误应该是  返回加过的时候json解析出了错，可以发下日志 或者检查下返回的数据结构，或者在demo源码的OSSHttpdns.m 114行上下 打印下 看看是怎么回事

**Comment by pushuhengyang** [comment]
> 各个系统版本都有崩溃，占比如下
> iOS12 68%
> iOS13 20%
> iOS11 9%
> iOS10 2%

这个错误应该是 返回数据的时候json解析出了错，可以发下日志 或者检查下返回的数据结构，请用最新版本  这里修改过的
