### ISSUE TITLE
POD 安装失败

### ISSUE THREAD

**Issue by wangkai598** [aliyun/aliyun-oss-ios-sdk#226]
$ /usr/local/bin/git clone https://github.com/aliyun/aliyun-oss-ios-sdk.git
     /var/folders/ky/x08l7vhx4s195vlrt_nlcjt00000gn/T/d20200216-3565-1adyyjw
     --template= --single-branch --depth 1 --branch release_2.9.2
     正克隆到 '/var/folders/ky/x08l7vhx4s195vlrt_nlcjt00000gn/T/d20200216-3565-1adyyjw'...

**Comment by wangkai598** [comment]
[!] Error installing AliyunOSSiOS
[!] /usr/local/bin/git clone https://github.com/aliyun/aliyun-oss-ios-sdk.git /var/folders/ky/x08l7vhx4s195vlrt_nlcjt00000gn/T/d20200216-3565-1adyyjw --template= --single-branch --depth 1 --branch release_2.9.2

正克隆到 '/var/folders/ky/x08l7vhx4s195vlrt_nlcjt00000gn/T/d20200216-3565-1adyyjw'...
error: RPC 失败。curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: 远端意外挂断了
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败

**Comment by pushuhengyang** [comment]
![image](https://user-images.githubusercontent.com/15009447/74804871-78da8d00-531c-11ea-9efa-454a84a4e7d4.png)
验证没有问题   网上查找可能buffer设置太小等几种原因   参考https://www.jianshu.com/p/49143a168971  或者https://www.jianshu.com/p/88259e9fa82d 
 或者试试  SSL  不用  https

**Comment by wangkai598** [comment]
> ![image](https://user-images.githubusercontent.com/15009447/74804871-78da8d00-531c-11ea-9efa-454a84a4e7d4.png)
> 验证没有问题 网上查找可能buffer设置太小等几种原因 参考https://www.jianshu.com/p/49143a168971 或者https://www.jianshu.com/p/88259e9fa82d
> 或者试试 SSL 不用 https

好的，多谢，换了个网络OK了

**Comment by pushuhengyang** [comment]
@wangkai598    那就好  那关闭这个issue吧
