### ISSUE TITLE
pod 失败

### ISSUE THREAD

**Issue by caopengfeiIOS** [aliyun/aliyun-oss-ios-sdk#238]
Installing AliyunOSSiOS (2.10.8)

[!] Error installing AliyunOSSiOS
[!] /usr/local/bin/git clone https://github.com/aliyun/aliyun-oss-ios-sdk.git /var/folders/q9/040thvzn7nn3r6q8q76fwqh00000gn/T/d20180622-36820-1hx6dfp --template= --single-branch --depth 1 --branch release_2.10.8

Cloning into '/var/folders/q9/040thvzn7nn3r6q8q76fwqh00000gn/T/d20180622-36820-1hx6dfp'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by Panshuyan** [comment]
And who to resolve it, Man?
