### ISSUE TITLE
什么时候能支持下swift和 carthage啊

### ISSUE THREAD

**Issue by offbye** [aliyun/aliyun-oss-ios-sdk#24]
什么时候能支持下swift和 carthage啊

swift项目配置Cartfile，增加
`github "aliyun/aliyun-oss-ios-sdk" ~> 2.1.4`

运行
 carthage  update
 carthage  build

报下面的错误：
** Skipped building aliyun-oss-ios-sdk due to the error:
Dependency "aliyun-oss-ios-sdk" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/aliyun/aliyun-oss-ios-sdk/issues/new

**Comment by xuyecan** [comment]
swift是天然支持的，Objective-c的framework都可以直接引入到swift工程。

**Comment by suesu123456** [comment]
swift项目使用carthage,官方下载AliyunOSSiOS.framework,手动引入

**Comment by suesu123456** [comment]
swift使用carthage,官方下载AliyunOSSiOS.framework，启动，还是报错Dependency "aliyun-oss-ios-sdk" has no shared framework schemes，请问有啥解决办法么？
