### ISSUE TITLE
Building for iOS Simulator, but the linked framework 'AliyunOSSiOS.framework' was built for iOS.

### ISSUE THREAD

**Issue by Ftrybe** [aliyun/aliyun-oss-ios-sdk#250]
Building for iOS Simulator, but the linked framework 'AliyunOSSiOS.framework' was built for iOS.
真机可以，模拟器不行咋搞。直接引入的

**Comment by wushuai1415** [comment]
framework是用脚本生成的吗

**Comment by Ftrybe** [comment]
> framework是用脚本生成的吗

对，buildiOSFramework.sh

**Comment by wushuai1415** [comment]
你看下打包的sdk支持x86吗

**Comment by Ftrybe** [comment]
> 你看下打包的sdk支持x86吗
arm64 armv7

**Comment by wushuai1415** [comment]
> > 你看下打包的sdk支持x86吗
> > arm64 armv7

你的电脑如果不是m1的话应该模拟器是x86的，重新打一个吧

**Comment by Ftrybe** [comment]
> > > 你看下打包的sdk支持x86吗
> > > arm64 armv7
> 
> 你的电脑如果不是m1的话应该模拟器是x86的，重新打一个吧

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: ./build/Release-iphoneos/AliyunOSSiOS.framework/AliyunOSSiOS and ./build/Release-iphonesimulator/AliyunOSSiOS.framework/AliyunOSSiOS have the same architectures (arm64) and can't be in the same fat output file

**Comment by wushuai1415** [comment]
![image](https://user-images.githubusercontent.com/18363357/105433438-8f0f6c80-5c94-11eb-9288-ba51992deeef.png)
xcodebuild -configuration Release -workspace "${PROJECT_NAME}.xcworkspace" -scheme "${TARGET_NAME}" -sdk iphonesimulator build SYMROOT="${WRK_DIR}" EXCLUDED_ARCHS="arm64"

**Comment by Ftrybe** [comment]
OK ,谢谢
