### ISSUE TITLE
Apple check use NSUserName may make app be in violation of the Apple Developer Program License Agreement 

### ISSUE THREAD

**Issue by zzzworm** [aliyun/aliyun-oss-ios-sdk#256]
We just receive a letter from apple review team, Our app use some api to collect user info:
`Specifically, your app uses algorithmically converted device and usage data to create a unique identifier in order to track the user. The device information collected by your app may include some of the following: NSLocaleLanguageCode, attributesOfItemAtPath:error:, sysctlnametomib, NSUserName, and getifaddrs.`
We find the OSSUtil use NSUserName() to getRelativePath, Can we avoid use this method? We do not use this method at all.Also I can't find any case in this sdk use it.

**Comment by LeeWongSnail** [comment]
> We just receive a letter from apple review team, Our app use some api to collect user info:
> `Specifically, your app uses algorithmically converted device and usage data to create a unique identifier in order to track the user. The device information collected by your app may include some of the following: NSLocaleLanguageCode, attributesOfItemAtPath:error:, sysctlnametomib, NSUserName, and getifaddrs.`
> We find the OSSUtil use NSUserName() to getRelativePath, Can we avoid use this method? We do not use this method at all.Also I can't find any case in this sdk use it.

Did you solve this problem? I also encountered the same problem

**Comment by huiguangjun** [comment]
fix in  https://github.com/aliyun/aliyun-oss-ios-sdk/commit/b83c97de27fbc85a629f58270f71fb40ed46888f

**Comment by huiguangjun** [comment]
release_2.10.9
