### ISSUE TITLE
OSSCustomSignerCredentialProvider 自签模式的疑问

### ISSUE THREAD

**Issue by beimen** [aliyun/aliyun-oss-ios-sdk#26]
OSS开发者你好，我现在在客户端将相关参数（请求方法、文件路径、MD5）提交给业务服务器，服务器会生成并返回对应的时间以及相应的 Signature，但是目前的 SDK 自签模式似乎没有提供接口修改请求的时间？请问是否有计划提供这种接口？
如果不提供这种接口，用户的手机时间不正确会导致无法使用 OSS 服务啊。

**Comment by xuyecan** [comment]
您可以测试下，在一个请求超时时，sdk会取得该请求server返回的标准时间，并将其置为参考值并进行重试。后续请求，都用这个新的时间进行。
