### ISSUE TITLE
macOS开发集成OSS报错

### ISSUE THREAD

**Issue by xiesha** [aliyun/aliyun-oss-ios-sdk#267]
mac客户端开发，按照开发文档pod这个库AliyunOSSOSX失败了，如果库名已修改，请告知，谢谢

**Comment by wushuai1415** [comment]
mac也用AliyunOSSiOS吧

**Comment by xiesha** [comment]
集成AliyunOSSiOS的时候报错提示不支持macOS，报错如下：The platform of the target `Tangce_macOS` (macOS 10.14) is not compatible with `AliyunOSSiOS (2.8.0)`, which does not support `macOS`.

**Comment by xiesha** [comment]
使用cocoapods集成的

**Comment by wushuai1415** [comment]
我这里没有问题啊，看下你的podfile

**Comment by xiesha** [comment]
source 'https://github.com/aliyun/aliyun-specs.git'
platform :osx, '10.14'
#use_frameworks!

target 'Tangce_macOS' do
  inhibit_all_warnings!         #禁止所有警告
  pod 'AliyunOSSiOS'
end

**Comment by xiesha** [comment]
podfile文件里面就是这样写的，其它类似`Masonry`都正常的，就是`AliyunOSSiOS`失败报错了，我在iOS项目中也正常集成没有问题的，现在macOS项目中报错了

**Comment by wushuai1415** [comment]
![image](https://user-images.githubusercontent.com/18363357/123028522-0f87f400-d412-11eb-86cd-a489aacf4867.png)
你使用的这个spec的platform只有ios

**Comment by wushuai1415** [comment]
![image](https://user-images.githubusercontent.com/18363357/123028655-4cec8180-d412-11eb-92ca-2621f5c3d079.png)
这是现在的版本

**Comment by xiesha** [comment]
非常感谢，我删除阿里的source，直接用cocoapods自己默认的source就好了，谢谢

**Comment by xiesha** [comment]
我不会关闭Issues，麻烦关闭一下我的Issues吧，谢谢

**Comment by jksniper** [comment]
> podfile文件里面就是这样写的，其它类似`Masonry`都正常的，就是`AliyunOSSiOS`失败报错了，我在iOS项目中也正常集成没有问题的，现在macOS项目中报错了
请问在iOS项目里导入报framework not found 怎么办

**Comment by xiesha** [comment]
正常方式不能pod的话，添加这个suorce看看source 'https://github.com/aliyun/aliyun-specs.git'
