### ISSUE TITLE
上传时设置maxConcurrentOperationCount无效

### ISSUE THREAD

**Issue by Huanhoo** [aliyun/aliyun-oss-ios-sdk#268]
我上传时client初始化的时候，给config设置了maxConcurrentOperationCount无效，实际并发数一直是4，我看默认是5，但是设置小于4或者大于4最后都是4，请问如何解决

**Comment by wushuai1415** [comment]
目前maxConcurrentOperationCount这个参数只是修改了内部维护的一个任务队列的并发数，没有修改NSURLSession的HTTPMaximumConnectionsPerHost。
