### ISSUE TITLE
OSSResumableUploadRequest 的uploadId 能否支持业务端传入？

### ISSUE THREAD

**Issue by yusanlou** [aliyun/aliyun-oss-ios-sdk#277]
目前即使传入id也会被覆盖，使用OSSInitMultipartUploadRequest 则会提示匿名用户无权限访问，导致最终取不到uploadId
![image](https://user-images.githubusercontent.com/13093664/133569777-d28597ad-2bdd-45a0-a341-40b8cd44023f.png)

**Comment by wushuai1415** [comment]
不支持，sdk不会使用request中uploadId

**Comment by wushuai1415** [comment]
不支持，sdk不会使用request中uploadId

**Comment by yusanlou** [comment]
哦，我看了下，也就是说如果要用OSSResumableUploadRequest，就要整个上传流程的request都替换成这个，但是有些情况下是由服务端进行任务初始化的，也就是说uploadId是服务端返回的，这就导致指定的recordDirectoryPath目录下没有存储uploadId

**Comment by wushuai1415** [comment]
那就只能改下源码自己做个组件了
