### ISSUE TITLE
Documentation about on what thread the progress handler and onContinoueBlock will be invoked.

### ISSUE THREAD

**Issue by soapsign** [aliyun/aliyun-oss-ios-sdk#28]
I would like to know on what thread those handlers will be invoked and is there any way we can specific the thread that those call will be on.

**Comment by xuyecan** [comment]
We have an NSOperationQueue in SDK, and all the tasks will run in this queue. Customizing the queue is not possible now, but you can limit the concurrency as the following code does:

```
OSSClientConfiguration * conf = [OSSClientConfiguration new];
conf.maxConcurrentRequestCount = 5;

OSSClient * client = [[OSSClient alloc] initWithEndpoint:ENDPOINT credentialProvider:credential1 clientConfiguration:conf];
```
