### ISSUE TITLE
在framework中使用pod引入后报错

### ISSUE THREAD

**Issue by daveeapp** [aliyun/aliyun-oss-ios-sdk#283]
dyld[44882]: Library not loaded: @rpath/AliyunOSSiOS.framework/AliyunOSSiOS

**Comment by TheLittleBoy** [comment]
pod 'AliyunOSSiOS', '~> 2.10.10'   我这没报错啊

**Comment by wushuai1415** [comment]
> dyld[44882]: Library not loaded: @rpath/AliyunOSSiOS.framework/AliyunOSSiOS

字面意思就是没加载到库，搜索一下Library not loaded有相关解决方案，没明白你说的这个在framework中使用pod是什么意思

**Comment by TheLittleBoy** [comment]
他是想打包一个自己的framework，然后里面用到了AliyunOSSiOS

**Comment by daveeapp** [comment]
> 他是想打包一个自己的framework，然后里面用到了AliyunOSSiOS

嗯，是的，我在自己的framework中使用pod引入AliyunOSSiOS，编译时没有异常，但是运行后就会报错；

**Comment by daveeapp** [comment]
> 他是想打包一个自己的framework，然后里面用到了AliyunOSSiOS

嗯，是的，我在自己的framework中使用pod引入AliyunOSSiOS，编译时没有异常，但是运行后就会报错；
现在的解决方式是将编译后的.framework文件拖到自己的framework工程中

**Comment by daveeapp** [comment]
> 他是想打包一个自己的framework，然后里面用到了AliyunOSSiOS

请问，你在framework中使用pod引用后，运行不报错吗？主工程的pod文件中是不是也引用了AliyunOSSiOS？我想要的是只在framework中pod引用，在主工程中不引用

**Comment by TheLittleBoy** [comment]
> > 他是想打包一个自己的framework，然后里面用到了AliyunOSSiOS
> 
> 请问，你在framework中使用pod引用后，运行不报错吗？主工程的pod文件中是不是也引用了AliyunOSSiOS？我想要的是只在framework中pod引用，在主工程中不引用

主工程中也要引入AliyunOSSiOS，要么你就把代码都考到你的framework里。
