### ISSUE TITLE
好麻烦啊

### ISSUE THREAD

**Issue by dd9913762113** [aliyun/aliyun-oss-ios-sdk#296]
简单的上传返回URL
竟然没有
不说其他的
一些功能可以弄的简单点吗？
都得弄那么麻烦
自己研发封装一遍
文档也不清不楚的
demo也写的明白点啊
demo弄好了，用的人数不就多了，也不会有这么多待解决的问题了
产品狗，会不会做oss SDK啊
用个SDK 真JB累，各种封装
那么多类，开发能用到几个？ 想的都是火箭，怎么把根本都忘了？

**Comment by dd9913762113** [comment]
简单的上传下载
搞你妹的这么复杂
能用一句话解决的事情
搞你妹的一大篇
设计这个SDK的人的脑子被驴踢了吗

**Comment by dd9913762113** [comment]
失败重传本来是挺好的功能
但别做成翔一样
要不你就别给我传
我自己处理都可以的
每次失败后后，我都得取消这个上传请求，坑

**Comment by MustangYM** [comment]
必须得点个赞, 哈哈哈!
