### ISSUE TITLE
NSOperation 多次快速调用[request cancel] 无法取消

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#3]
实现一个NSOperation, 在Operation里面上传文件,   运行一个CFRunLoopRun() (使用RunLoop等待上传完成, 同时接收外面的暂停事件).   如果此时接收到外部的取消事件, 则立即调用 [request cancel]  和CFRunLoopStop(CFRunLoopGetCurrent()) 结束这个NSOperation.   如果外部希望重新开始上传, 则创建一个新的OPeration上传同一个文件.    如此切换, 前面1,2次能成功, 后面不能成功, 发现一直在上传.     我必须等待continueWithBlock事件之后再结束RunLooper才不会发生这样的情况.   虽然我找到绕过的方法了, 但是希望你们解决一下. 

你们可以实现这样的一个Demo试一下:
一个按钮: 一个暂停状态, 一个继续状态, 继续时把operation添加进运行.   暂停时调用cancel和stopRunLoop.   
一个OperationQueue, 同时只有一个Opeation运行, 上传同一个文件, 使用putObject方法.

这个按钮去监听任务上传的状态, 如果正在上传, 显示暂停, 停止上传, 显示继续.

然后一直点, 迅速点,多次点这个按钮, 如果cancel时同时stop了RunLoop, 就会无法停止上传文件.   要等你们的取消的结束的Block回调再Stop runloop, 才能正常运作.

如果不能解决这个Bug, 希望其他人开发时能看到这个坑,我的工程里面是必现的.

**Comment by xuyecan** [comment]
已跟进这个问题，有进展我在这里回复。
