### ISSUE TITLE
和facebook库有冲突啊

### ISSUE THREAD

**Issue by zerozhu** [aliyun/aliyun-oss-ios-sdk#30]
duplicate symbol _kBFMultipleErrorsError in:
    **/Build/Products/Debug-iphonesimulator/libAliyunOSSiOS.a(OSSTask.o)
    **/FacebookSDK.framework/FacebookSDK(Bolts.o)
duplicate symbol _warnBlockingOperationOnMainThread in:
    **/Build/Products/Debug-iphonesimulator/libAliyunOSSiOS.a(OSSTask.o)
    **/FacebookSDK.framework/FacebookSDK(BFTask.o)
ld: 2 duplicate symbols for architecture x86_64

**Comment by xuyecan** [comment]
收到，将尽快解决这个问题。

**Comment by ccoding2015** [comment]
解决没呢？都等着呢 😁

**Comment by xuyecan** [comment]
已在 commit [a55b33b](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/a55b33b98f99be1e448c03feb0c6498a1a6f9445) 中解决，可自行打包，也可等到下一个版本发布~

**Comment by xuyecan** [comment]
请使用 pod 'AliyunOSSiOS',  '2.5.1'

**Comment by ccoding2015** [comment]
pod search 还没有。还没更新好吗？麻烦了。我这着急哈 😄
