### ISSUE TITLE
视频上传先走了成功回调，调用后端接口保存数据之后出现了问题。但是这个时候 阿里云是上传成功的

### ISSUE THREAD

**Issue by 835932621** [aliyun/aliyun-oss-ios-sdk#300]
pod 'AliyunOSSiOS', '2.10.8'

阿里云上没有保存的视频路径文件

**Comment by 835932621** [comment]
上传代码如下：
OSSPutObjectRequest * put = [OSSPutObjectRequest new];
    put.bucketName = @"***";
    put.objectKey = self.fileName;
    put.uploadingFileURL = [NSURL fileURLWithPath:self.video_urlPath];
   
    WeakSelf;
    put.uploadProgress = ^(int64_t bytesSent, int64_t totalByteSent, int64_t totalBytesExpectedToSend) {
        // 当前上传段长度、当前已经上传总长度、一共需要上传的总长度
        NSLog(@"当前上传段长度===%lld,当前已经上传总长度===%lld, 一共需要上传的总长度===%lld", bytesSent, totalByteSent, totalBytesExpectedToSend);
    };
    OSSTask * putTask = [self.clients putObject:put];
    ////阻塞上传线程  直到上传完成
    // [putTask waitUntilFinished];
    
    [putTask continueWithBlock:^id(OSSTask *task) {
        task = [self.clients presignPublicURLWithBucketName:@"daojiale" withObjectKey:self.fileName];
        if (!task.error) {
            NSLog(@"upload object success!");
            
            [weakSelf videoSave];
        } else {
            
            NSLog(@"upload object failed, error: %@" , task.error);
            [SVProgressHUD dismiss];
            [SVProgressHUD showErrorWithStatus:@"视频上传失败！"];
            return nil;
        }
        return nil;
    }];
    
    这个问题是我司审核同事发现的，极少部分。 并不是所有人都是这个样子

**Comment by wushuai1415** [comment]
没明白是什么问题

**Comment by 835932621** [comment]
就是上传视频到阿里云 走了成功回调 我们把这个上传任务结果同步到了后台，但是后面去审核视频的时候 发现这个视频在阿里云上并没有。

**Comment by wushuai1415** [comment]
> 就是上传视频到阿里云 走了成功回调 我们把这个上传任务结果同步到了后台，但是后面去审核视频的时候 发现这个视频在阿里云上并没有。

bucketName、objectKey、requestID、上传的时间段 这些信息有吗

**Comment by 835932621** [comment]
requestID:622700253E9D1A3236B0F564
objectKey:/house/video/197458/24720_1641435785.mp4
bucketName:A6_CQ

**Comment by 835932621** [comment]
访问视频路径的时候报错提示如下：
<Error>
<Code>InvalidBucketName</Code>
<Message>The specified bucket is not valid.</Message>
<RequestId>622700253E9D1A3236B0F564</RequestId>
<HostId>oss-cn-hangzhou.aliyuncs.com</HostId>
<BucketName>A6_CQ</BucketName>
</Error>

**Comment by 835932621** [comment]
上面的是直连阿里云的路径 ，

下面这个是我们公司映射阿里云视频地址的链接报错提示：
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>62270238C8A4583835E5CA42</RequestId>
<HostId>daojiale.oss-cn-hangzhou.aliyuncs.com</HostId>
<Key>A6_CQ/house/video/197458/24720_1641435785.mp4</Key>
</Error>

**Comment by wushuai1415** [comment]
> /house/video/197458/24720_1641435785.mp4

![image](https://user-images.githubusercontent.com/18363357/157186119-850f9190-2eeb-488c-a236-a56be2f93d55.png)
你这个代码有些问题，if里判断的task不是put的task，而是生成url的task，如果put失败了，而生成url成功了就会出问题

**Comment by 835932621** [comment]
阿里云的demo 里面就是这样写的啊 😢，正确应该修改成啥啊

**Comment by wushuai1415** [comment]
> [putTask continueWithBlock:^id(OSSTask *task) {
>     task = [self.clients presignPublicURLWithBucketName:@"***" withObjectKey:self.fileName];
>     if (!task.error) {
>         NSLog(@"upload object success!");
>         
>         [weakSelf videoSave];
>     } else {
>         
>         NSLog(@"upload object failed, error: %@" , task.error);
>         [SVProgressHUD dismiss];
>         [SVProgressHUD showErrorWithStatus:@"视频上传失败！"];
>         return nil;
>     }
>     return nil;
> }];

[putTask continueWithBlock:^id(OSSTask *task) {
	// 上传成功
	if (!task.error) {
    	OSSTask *presignUrlTask = [self.clients presignPublicURLWithBucketName:@"***" withObjectKey:self.fileName];
		// 生成url成功
		if (!presignUrlTask.error) {
			...
		} else { // 生成url失败
			...
		}
	} else { //上传失败
		...
	}
    return nil;
}];
你说的demo是指哪个demo，我看下需不需要改掉

**Comment by 835932621** [comment]
https://help.aliyun.com/document_detail/94408.html 这里

**Comment by 835932621** [comment]
具体的涉及到OSS的demo  我这找不到了

**Comment by 835932621** [comment]
对了 那我们还需要升级 AliyunOSSiOS 到最新的2.10.12 这个版本吗

**Comment by wushuai1415** [comment]
> 对了 那我们还需要升级 AliyunOSSiOS 到最新的2.10.12 这个版本吗

不需要

**Comment by 835932621** [comment]
好的 谢谢🙏

**Comment by 835932621** [comment]
对了 我要是使用 waitUntilFinished这个阻塞的话 是不是就不会有这个问题了

**Comment by wushuai1415** [comment]
> 对了 我要是使用 waitUntilFinished这个阻塞的话 是不是就不会有这个问题了

生成url接口只是本地的一个拼接逻辑，这个接口不会去请求oss上是否有这个文件

**Comment by 835932621** [comment]
OK 那就是我加上这个判断就行了嘛。 你们的文档需要及时更新一下哦   我想肯定还有其他人遇到过这个问题的 😼
