### ISSUE TITLE
无网络删除图片Block无法回调

### ISSUE THREAD

**Issue by songzhongz** [aliyun/aliyun-oss-ios-sdk#31]
开始上传照片时断开网络连接进入飞行模式，- (OSSTask *)continueWithBlock:(OSSContinuationBlock)block 方法block永久不会回调，页面上的loading弹窗无法消失。

**Comment by xuyecan** [comment]
一直没办法复现，可否提供测试工程呢？

**Comment by sfandy126** [comment]
> 开始上传照片时断开网络连接进入飞行模式，- (OSSTask *)continueWithBlock:(OSSContinuationBlock)block 方法block永久不会回调，页面上的loading弹窗无法消失。

这个问题还在，请问怎么解决？最新版本2.11.0
