### ISSUE TITLE
上传超过10M文件，就会提示文件大小超过限制，但没有找到相关配置关闭限制

### ISSUE THREAD

**Issue by misaka14** [aliyun/aliyun-oss-ios-sdk#311]
![image](https://user-images.githubusercontent.com/10043184/164966509-7074a315-68cc-4e58-9fb3-bd9511d0aafd.png)

**Comment by wushuai1415** [comment]
这是sdk返回的错误？

**Comment by misaka14** [comment]
不是，原来是设置了 callbackvar和 callbackparam 参数，自家公司服务器做了限制。。。
