### ISSUE TITLE
赶紧出Swift版本呀。

### ISSUE THREAD

**Issue by zdd** [aliyun/aliyun-oss-ios-sdk#37]
期待。

**Comment by henry0475** [comment]
哎，混编吧

**Comment by xuyecan** [comment]
请问使用混编调用遇到什么问题了吗？

**Comment by zdd** [comment]
@xuyecan 没有遇到问题，只是我有代码强迫症，尽量不混编。

**Comment by xuyecan** [comment]
嗯，我们已经了解到了您的需求，我们会尽快规划，请关注官网公告~

**Comment by 1019272778** [comment]
有swift 版本了啊
https://bbs.aliyun.com/read/314674.html?spm=5176.bbsl211.0.0.OKRWmc
