### ISSUE TITLE
bitcode bundle could not be generated

### ISSUE THREAD

**Issue by JustFavor** [aliyun/aliyun-oss-ios-sdk#39]
bitcode bundle could not be generated because '/ios/AliyunOSSiOS.framework/AliyunOSSiOS(OSSTaskCompletionSource.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64  我按照网上提供的在Other C Flags 添加-fembed-bitcode 也没能解决

**Comment by xuyecan** [comment]
可否暂时通过引入源码的方式解决？我这边bitcode都是开着的，不知道怎么引入了这个异常，我要再排查一下。

**Comment by JustFavor** [comment]
重新编译源代码 可以打包

**Comment by xuyecan** [comment]
已经找到问题，将在下个版本解决。多谢反馈！
