### ISSUE TITLE
STS Token鉴权什么时候可以开始用? 

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#4]
AK/SK鉴权效率非常低下, 我测试MultipartUploadRequest上传时(resumableUploadFile这个函数), 发现每一次progress回调, 都会向服务器请求一次签名. 这样效率非常低, 而且我们服务器压力也非常大.  能不能优化SDK.

目前STS Token这种方式还用不了是吧?

**Comment by com314159** [comment]
RAM 这个服务还在公测中, STS Token依赖于RAM

**Comment by xuyecan** [comment]
申请公测资格后就可以开始用了，审批应该很快的。
http://www.aliyun.com/product/ram
