### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by juningwei** [aliyun/aliyun-oss-ios-sdk#41]
你们昨天修改了关于适配https的东西，但现在cocoapods上面还不是最新版吧。

**Comment by SducodeMonkey** [comment]
昨天的变更是针对demo里HTTPS下WebView+SNI场景的适配优化，SDK还没有更新的；
HTTPDNS的iOS SDK需要从控制台下载。

**Comment by xuyecan** [comment]
现在2.6.0已经发布，请更新~
