### ISSUE TITLE
我将Framework拖进我的工程，发现有这个问题。

### ISSUE THREAD

**Issue by leewaycn** [aliyun/aliyun-oss-ios-sdk#46]
Undefined symbols for architecture arm64:
  "_res_9_getservers", referenced from:
      -[OSSIPv6Adapter getDNSServersIpStack] in AliyunOSSiOS(OSSIPv6Adapter.o)
  "_res_9_ninit", referenced from:
      -[OSSIPv6Adapter getDNSServersIpStack] in AliyunOSSiOS(OSSIPv6Adapter.o)
  "_res_9_ndestroy", referenced from:
      -[OSSIPv6Adapter getDNSServersIpStack] in AliyunOSSiOS(OSSIPv6Adapter.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xuyecan** [comment]
这一步: https://github.com/aliyun/aliyun-oss-ios-sdk#兼容ipv6-only网络 做了吗？

**Comment by Nirvana-icy** [comment]
@leewaycn  try to add link binary with libraries with libresolv.tbd

**Comment by gemscng** [comment]
It seems happened on simulator only. Anyone able to solve this?
