### ISSUE TITLE
打包framework时错误

### ISSUE THREAD

**Issue by Homosum** [aliyun/aliyun-oss-ios-sdk#49]
Build settings from command line:
    SDKROOT = iphoneos10.2
    SYMROOT = ./build

xcodebuild: error: The project named "AliyunOSSiOS" does not contain a scheme named "AliyunOSSiOS". The "-list" option can be used to find the names of the schemes in the project.
Build settings from command line:
    SDKROOT = iphonesimulator10.2
    SYMROOT = ./build

xcodebuild: error: The project named "AliyunOSSiOS" does not contain a scheme named "AliyunOSSiOS". The "-list" option can be used to find the names of the schemes in the project.
cp: ./build/Release-iphoneos/AliyunOSSiOS.framework: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: ./build/Release-iphoneos/AliyunOSSiOS.framework/AliyunOSSiOS (No such file or directory)
rm: ./build: No such file or directory

**Comment by 1019272778** [comment]
@Homosum 请问现在还有这样的问题吗？
