### ISSUE TITLE
resumableUploadFile  recordKey的Bug

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#5]
原代码:  

       [NSString stringWithFormat:@"%@-%@-%@-%@", bucketName, objectKey, filePath, lastModified];

其中filePath这一句是有Bug的.  filePath在iOS里面是有沙盒机制的,前面的路径每次运行都是随机的, 不能去记录一个完整的路径, 会有Bug. 

如:

/Users/gzc/Library/Developer/CoreSimulator/Devices/FA0B0EC6-9366-4905-B9C1-E80DAF59EBC4/data/Containers/Data/Application/9C6F610E-D902-4450-AB8E-CA69C3F1A61A/Documents/jaxusData/userData/5617a1218a2f2d2c0c054925/publishAsset/image/66E6027E-ABDE-431B-A3FF-15251502CF3E-2015-10-22

上面的路径中, 只有/Documents/jaxusData/userData/5617a1218a2f2d2c0c054925/publishAsset/image/66E6027E-ABDE-431B-A3FF-15251502CF3E-2015-10-22这个是固定的.

而其变化的是:/9C6F610E-D902-4450-AB8E-CA69C3F1A61A这一段.

以上为模拟器的测试结果, 每次运行都会变化.

真机应该是类似的.

请你们处理一下

**Comment by xuyecan** [comment]
已处理，谢谢指出。see [#eca6748](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/eca6748489516f53ae1a7e6a11504e07e95d275e)。
