### ISSUE TITLE
使用cocoasPod也装不了

### ISSUE THREAD

**Issue by Homosum** [aliyun/aliyun-oss-ios-sdk#50]
Unable to satisfy the following requirements:

- `AliyunOSSiOS (~> 2.6.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `AliyunOSSiOS (~> 2.6.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by 1019272778** [comment]
亲自测试是可以的，能否提供更多的错误信息呢？

**Comment by george012** [comment]
同样的问题

**Comment by duan007a** [comment]
@george012 @Homosum 首先执行pod repo update ,然后cd到工程文件目录下，执行pod update应该就可以了

**Comment by george012** [comment]
这个问题已经解决好久了 其实问题根源在 你们github代码及发布版本更新后  cocoapod repos线上缓存库更新不及时导致的 具体因为什么不及时1 开发人员没有及时提交“pod trunk push”处理sdk库  2网络缓存更新周期太长




谢谢您哈


在2017年11月13 16时50分, "润生"<notifications@github.com>写道:



@george012@Homosum 首先执行pod repo update ,然后cd到工程文件目录下，执行pod update应该就可以了

**Comment by 1019272778** [comment]
感谢。我们看一下我们的发布流程是否有问题。

**Comment by 1019272778** [comment]
更多信息可以参见：http://www.jianshu.com/p/1d058d224cad

**Comment by mengrant** [comment]
几年前的问题，又出现了？

**Comment by magic3584** [comment]
Same again
