### ISSUE TITLE
                                                             批量上传的问题                                                                                                         批量上传                                                          

### ISSUE THREAD

**Issue by suochenhe** [aliyun/aliyun-oss-ios-sdk#52]
同时上传两张图片,一张以put.uploadingData的方式上传,一张以put.uploadingFileURL的方式上传,只会成功一张,而且有一个上传,不会触发成功和失败的回调

**Comment by 1019272778** [comment]
请问是什么场景下会有如上的操作呢？

**Comment by suochenhe** [comment]
比如我要上传一本书（包含封面，CIP，内容页），书的封面和CIP是从前面页面传过来的，由于传递的model该字段为NSString所以传过来的是本地图片路径，最后一个页面是拍摄或者选择书内容的图片，可以直接拿到 NSData的图片，上传一本书必须要 封面，CIP，内容页（至少一页）同时上传成功，才能请求我们的服务器去添加这本书，当同时上传封面，CIP，内容页时，就会出现这样的操作

**Comment by 1019272778** [comment]
ok。我们先对批量上传的接口进行验证看看。
另， 可以试一下同步顺序上传看看是否可以解决这个问题。

**Comment by lieyunye** [comment]
我也遇到了，都用put.uploadingData解决了

**Comment by julianL0veios** [comment]
确实有该问题 谢谢lieyunye
