### ISSUE TITLE
用OSSFederationCredentialProvider获取token时报错；

### ISSUE THREAD

**Issue by songsh** [aliyun/aliyun-oss-ios-sdk#59]
OSSCredentialProvider credentialProvider = new OSSFederationCredentialProvider() {
            @Override
            public OSSFederationToken getFederationToken() {
                return getToken();
            }
        };

Can't get a federation token
 Encounter local execpiton: java.io.IOException: Can't get a federation token
Can't get a federation token

**Comment by 1019272778** [comment]
@songsh 
是使用android sdk报错吗？可以提一下具体使用的代码吗？另，也可以在android sdk 开一个issue
