### ISSUE TITLE
resumableUploadFile 上传小文件取消后无法再次恢复

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#6]
小文件, 只有一个分块, 如果取消了, 之后重试时, 一直是错误的. 原因如下:

小文件重试时, 查询到的OSSListPartsResult格式并不是普通的格式
    Printing description of result->_parts:
{
    ETag = "\"0654ECA0DA09B0B95BC32B73072B002D\"";
    LastModified = "2015-10-22T06:31:39.000Z";
    PartNumber = 1;
    Size = 166328;
}

此时调用以下代码会一直失败 , 因为这个Dic的key全对应不上, 所以之后一直无法再成功了. 

                 [result.parts enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
                    NSDictionary * dict = obj;
                    uploadedLength += [[dict objectForKey:OSSSizeXMLTOKEN] longLongValue];
                }];

望解决. 谢谢.

**Comment by com314159** [comment]
请自行测试 part number为1时, 上传取消, 继续时的结果, 其返回格式是NSDictionary, 而不是NSArray

**Comment by com314159** [comment]
经查找, 当part number为1时, 后台返回了一个Dict, 而当part number 为>=1时, 后台返回了一个数组.

**Comment by com314159** [comment]
修复方法, 在OSSModel.m中, 判断返回的是NSArray还是Dictionary

                   listPartsReuslt.nextPartNumberMarker = [[parsedDict objectForKey:OSSNextPartNumberMarkerXMLTOKEN] intValue];
                    listPartsReuslt.maxParts = [[parsedDict objectForKey:OSSMaxKeyXMLTOKEN] intValue];
                    listPartsReuslt.isTruncate = [[parsedDict objectForKey:OSSMaxKeyXMLTOKEN] boolValue];
                    id object = [parsedDict objectForKey:OSSPartXMLTOKEN];
                    
                    if ([object isKindOfClass:[NSArray class]]) {
                        listPartsReuslt.parts = object;
                    } else if ([object isKindOfClass:[NSDictionary class]]) {
                        NSMutableArray *array = [[NSMutableArray alloc] init];
                        [array addObject:object];
                        listPartsReuslt.parts = array;
                    } else {
                        listPartsReuslt.parts = nil;
                    }

**Comment by xuyecan** [comment]
已修复，见 [#3806136](https://github.com/aliyun/aliyun-oss-ios-sdk/commit/3806136aaa4eca3547b64e6c3aa352d4ada707f4)。
