### ISSUE TITLE
在对私有Bucket签名时会一直阻塞主线程

### ISSUE THREAD

**Issue by huanglei1926** [aliyun/aliyun-oss-ios-sdk#60]
NSString * constrainURL = nil;
    OSSTask * task = [client presignConstrainURLWithBucketName:bucketName withObjectKey:objectKey withExpirationInterval: 30 * 60];
    if (!task.error) {
        constrainURL = task.result;
    } else {
        NSLog(@"error: %@", task.error);
    }
    return constrainURL;

在通过如上代码进行私有Bucket加签时,程序主线程会被阻塞,并且打印了如下log:
Warning: A long-running operation is being executed on the main thread. 
 Break on warnBlockingOperationOnMainThread() to debug.

请问这是什么原因造成的?该怎么解决?

**Comment by 1019272778** [comment]
@huanglei1926 
你好，presignConstrainURLWithBucketName 这个函数中并没有耗时的io操作。都是一些算法操作。可以debug看看具体是走到哪一步比较耗时了吗？

**Comment by huanglei1926** [comment]
@1019272778 谢谢了,问题已经已经解决了,将此代码放入异步线程就好了
- (NSString *)getSecretUrlWithBucketName:(NSString *)bucketName withObjectKey:(NSString *)objectKey
{
    NSString * constrainURL = nil;
    OSSTask * task = [client presignConstrainURLWithBucketName:bucketName withObjectKey:objectKey withExpirationInterval: 30 * 60];
    if (!task.error) {
        constrainURL = task.result;
    } else {
        NSLog(@"error: %@", task.error);
    }
    return constrainURL;
}

dispatch_async(dispatch_get_global_queue(0, 0), ^{
                        NSString *url = [[SCAliyunOSSTool sharedInstance] getSecretUrlWithBucketName:AliyunOSSBucketNameAuth withObjectKey:imageName];
                    });

**Comment by 1019272778** [comment]
ok.我们也关注签名效率和消耗时间。如果不能优化，看看是否提供一个异步方法。
