### ISSUE TITLE
swift sdk ListObjectsRequest 出错

### ISSUE THREAD

**Issue by liuliangjia** [aliyun/aliyun-oss-ios-sdk#63]
//这个可以执行成功。
        let getObjectRequest=GetObjectRequest(bucketName: "shabmp3",key: "凯叔声律启蒙/")
        oss.getObject(request: getObjectRequest){
            (success,result,error) in
            if success {
                print(result?.content)
            }else{
                print(error)
            }
        }
        
//这个就报错
        var listObjectsRequest=ListObjectsRequest(bucketName: "shabmp3")
        oss.listObjects(request: listObjectsRequest){
            (success,result,error) in
            if success {
                print("success")
            }else{
                print(error)
            }
        }

**Comment by 1019272778** [comment]
@liuliangjia 
具体的错误信息是什么呢？
