### ISSUE TITLE
批量上传多张高质量图片内存急剧增加导致app闪退

### ISSUE THREAD

**Issue by RobertHuoShan** [aliyun/aliyun-oss-ios-sdk#64]
业务描述：一款摄影师app, 需要上传大量的图片到OSS上面，将10M-20M的原片压缩到1-2M之后，然后一次性选择500张1-2M的图片上传到OSS上面。

问题描述: 选择了大量高质量图片之后，会导致内存瞬间暴增，最终导致APP闪退。

解决思路：从相册选取照片的时候，将10-20M的图片压缩到100KB左右的照片，显示在collectionView上面，因为这样选择的是缩略图，所以不会导致内存暴增，可以将几百张图片顺利展示在collectionView上。
然后，在图片上传的时候，将10M-20M的原片压缩到1-2M之后上传，上传了4-5张图片之后，就会出现app闪退，后面找出原因是因为 [putTask waitUntilFinished] 阻塞了线程，如果注释掉这句代码可以将几百上图片上传，但是中途会导致某些照片实际上面没有上传。

问题：OSS如何批量上传多张高质量图片？？？求大神指导。

**Comment by RobertHuoShan** [comment]
联系方式QQ：498441403

**Comment by 1019272778** [comment]
能贴一下你使用oss 的代码吗？

**Comment by JacKFJ** [comment]
我和你差不多，下载大量文件，包括图片，内存飙升，程序卡死

**Comment by RobertHuoShan** [comment]
苹果官方提供了一个下载高清图片的demo，你可以去看下。

**Comment by 1019272778** [comment]
@RobertHuoShan 
所以您的问题是oss 层的问题吗？

**Comment by RobertHuoShan** [comment]
这个应该是iOS系统自身加载图片的问题，跟OSS无关，但是如果OSS能提供一个解决办法那更好，因为这个会影响OSS的使用。

**Comment by JacKFJ** [comment]
我是纯粹的下载到本地，不是大量加载显示图片的
