### ISSUE TITLE
时间校对逻辑应该去掉

### ISSUE THREAD

**Issue by lazyjean** [aliyun/aliyun-oss-ios-sdk#68]
NSString * dateStr = [[httpResponse allHeaderFields] objectForKey:@"Date"];
    if ([dateStr length]) {
        NSDate * serverTime = [NSDate oss_dateFromString:dateStr];
        NSDate * deviceTime = [NSDate date];
        NSTimeInterval skewTime = [deviceTime timeIntervalSinceDate:serverTime];
        [NSDate oss_setClockSkew:skewTime];
    } else {
        OSSLogError(@"date header does not exist, unable to adjust the time skew");
    }

以上代码是现在SDK中的时间校对逻辑，我们这边在使用了CDN后，CDN缓存了整个请求，这个逻辑会拿CDN的时间来校对本地的时间，由于CDN的响应时间是不更新的，所以这个逻辑会导致本地的时间错乱，建议使用专用的时间服务器来校对时间

**Comment by 1019272778** [comment]
@lazyjean 
oss server端会对访问的请求进行时间效验。如果请求的时间和服务器时间差距过大会认为请求超出了时间。因为在端上无法保证用户的时间（可能会自己调整时间）。所以有了这个时间效对的逻辑。
