### ISSUE TITLE
uploadId 应该由外部来管理

### ISSUE THREAD

**Issue by com314159** [aliyun/aliyun-oss-ios-sdk#7]
目前uploadId是由resumableUploadFile这个函数通过UserDefault来管理的.  看似没什么问题, 其实导致了两个严重的问题:

1. 外部无法控制应该继续上传还是重新上传. 虽然有判断文件的修改时间, 但是文件的修改时间这个属性是可以修改的. 这导致了一个隐性的Bug. 

2. 如果一个文件上传了一部分, 被删除了, 导致了userDefault的泄露. 

经过我的测试, 我测试了1000多个上传, 后面发现, userDefault里面有大量的recordKey, 虽然只占用了用户少量的空间, 但是积少成多, 而且永久不可删除. 

虽然我没有给出更好的设计方法. 我目前的实现是这样的. 可能还有更好的设计方法, 希望你们改进.

       /**
     *  @param resumableUploadId 如果传入nil, 不会继续上传, 如果传入与上次未成功相同的值, 将会继续           上次未完成的上传
     */
     - (OSSTaskHandler *)uploadFileResumable:(NSString *)filePath
                            resumableId:(NSString *)resumableUploadId
                        withContentType:(NSString *)contentType
                         withObjectMeta:(NSDictionary *)meta
                           toBucketName:(NSString *)bucketName
                            toObjectKey:(NSString *)objectKey
                            onCompleted:(void(^)(BFTask *task,NSString *resumableUploadId))onCompleted
                             onProgress:(void(^)(float progress))onProgress;

**Comment by xuyecan** [comment]
谢谢你的建议。事实上，SDK现在的resumableUpload接口是为了兼容旧版本SDK而设计的。

现在版本的SDK更鼓励用户通过封装好的分块上传接口，实现自己的断点续传。

**Comment by xuyecan** [comment]
已经加入由用户自行管理UploadId的断点续传接口：
```
[OSSClient resumableUpload:(OSSResumableUploadRequest *)];
```
