### ISSUE TITLE
swift4编译错误

### ISSUE THREAD

**Issue by zidong0822** [aliyun/aliyun-oss-ios-sdk#70]

**Comment by 1019272778** [comment]
@zidong0822 
具体有什么错误提示吗？

**Comment by 1019272778** [comment]
如果还有什么问题，可以参见如下文章：
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/index.html#//apple_ref/doc/uid/TP40014216-CH2-ID0
