### ISSUE TITLE
duplicate symbol _kReachabilityChangedNotification

### ISSUE THREAD

**Issue by dragontianxia** [aliyun/aliyun-oss-ios-sdk#73]
duplicate symbol _kReachabilityChangedNotification in:
    /Users/xxx/Library/Developer/Xcode/DerivedData/XXXXX-cjebifplkqpksbfvvsreblbsyefu/Build/Products/Debug-iphonesimulator/AliyunOSSiOS/libAliyunOSSiOS.a(OSSReachability.o)
    /Users/xxx/Library/Developer/Xcode/DerivedData/XXXXX-cjebifplkqpksbfvvsreblbsyefu/Build/Products/Debug-iphonesimulator/Reachability/libReachability.a(Reachability.o)

**Comment by 1019272778** [comment]
https://www.zhihu.com/question/20728615
可以参考这个方案
