### ISSUE TITLE
duplicate symbol _ossReachabilityChangedNotification in:

### ISSUE THREAD

**Issue by Chenjm08** [aliyun/aliyun-oss-ios-sdk#75]
SLAliyunManager.framework依赖AliyunOSSiOS，XStarSDK依赖AliyunOSSiOS和SLAliyunManager.framework。
运行XStarSDK会出现以下错误，怀疑是因为ossReachabilityChangedNotification是全局变量的原因导致以下问题，但是不知道怎么解决，请求帮助～

duplicate symbol _ossReachabilityChangedNotification in:
    /Users/admin/Library/Developer/Xcode/DerivedData/XStarSDK-guyaekoszrbimkbushwwnkerawqg/Build/Products/Release-iphoneos/AliyunOSSiOS/libAliyunOSSiOS.a(OSSReachability.o)
    /Users/admin/Documents/Project/XStarSDK/Example/Pods/SLAliyunManager/SLAliyunManager/Assets/SLAliyunManager.framework/SLAliyunManager(OSSReachability.o)

ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Chenjm08** [comment]
问题已经解决，是由于ossReachabilityChangedNotification被定义为全局变量造成的。改成用const修饰就没问题了。

**Comment by duan007a** [comment]
@Chenjm08 可以参考一下这里http://blog.csdn.net/numbbuaa/article/details/8626843
