### ISSUE TITLE
上传图片成功，但是图片出现损坏

### ISSUE THREAD

**Issue by SillyLong** [aliyun/aliyun-oss-ios-sdk#89]
OSSPutObjectRequest *objectRequest = [OSSPutObjectRequest new];

	objectRequest.bucketName = anObject.bucketName;

	objectRequest.objectKey = anObject.objectKey;

	objectRequest.uploadingFileURL = [NSURL URLWithString:path];

    objectRequest.contentEncoding = [OSSUtil base64Md5ForFilePath:path];

objectRequest.uploadProgress = ^(int64_t bytesSent, int64_t totalByteSent, int64_t totalBytesExpectedToSend)  {};

OSSTask *task = [self.client putObject:objectRequest];

 [task continueWithBlock:^id(OSSTask *task) {
};
上传图片的部分代码。

能够上传成功，但是有时候会有损坏的图片。
http://blog.csdn.net/blog_jihq/article/details/49679593 不知道是不是类似于这种问题

**Comment by 1019272778** [comment]
@SillyLong 
感谢提供信息，我们先检查一些代码。
另我们的上传回调中是带有md5信息的，可以用来检验。我们的上传测试用例中也有md5检查。

这个有时候能大概提供一个范围吗？

**Comment by SillyLong** [comment]
@1019272778 
范围不是很确定，就很少情况会这样

**Comment by 1019272778** [comment]
@SillyLong 收到。我们看看是否能添加一些自动检查的机制

**Comment by HuaZao** [comment]
遇到同样的问题,用开发者模式模拟非常差的网络,会频繁重现这个问题

**Comment by 1019272778** [comment]
@HuaZao 
2.8.0 版本已经开启了crc64的效验功能。也可以通过CRC验证。

**Comment by SillyLong** [comment]
@1019272778 谢谢，我试试看

**Comment by SillyLong** [comment]
@1019272778 试过了，加了crc64校验有时候还是也没用

**Comment by SillyLong** [comment]
@HuaZao 开启MD5可以解决？是怎么开启？

**Comment by duan007a** [comment]
@SillyLong 请问您在开启crc64校验时，使用- (OSSTask *)putObject:(OSSPutObjectRequest *)request上传出完成，确认一下是task.error为null吗，如果crc64验证不能通过的时候会有error产生的。
