### ISSUE TITLE
can't buildframework

### ISSUE THREAD

**Issue by hegelsu** [aliyun/aliyun-oss-ios-sdk#92]
Build settings from command line:
    SDKROOT = iphoneos11.1
    SYMROOT = ./build

xcodebuild: error: 'AliyunOSSSDK iOS.xcodeproj' does not exist.
Build settings from command line:
    SDKROOT = iphonesimulator11.1
    SYMROOT = ./build

xcodebuild: error: 'AliyunOSSSDK iOS.xcodeproj' does not exist.
cp: ./build/Release-iphoneos/AliyunOSSSDK iOS.framework: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: ./build/Release-iphoneos/AliyunOSSSDK iOS.framework/AliyunOSSSDK iOS (No such file or directory)
rm: ./build: No such file or directory

**Comment by duan007a** [comment]
@hegelsu 谢谢您的问题反馈! 我们已经修复掉脚本中的问题。请更新到master分支的最新commit，然后重试编译脚本就可以了
