### ISSUE TITLE
other linker flags 添加后 编译报错

### ISSUE THREAD

**Issue by maltsugar** [aliyun/aliyun-oss-ios-sdk#93]

**Comment by duan007a** [comment]
@maltsugar  能否提供一下您当前使用的版本，具体说一下您在Other Linker Flags处进行了什么操作,然后具体的报错信息也请提供一下，我们好跟进一下问题？

**Comment by maltsugar** [comment]
不好意思。是xcode 9 的bug，添加-ObjC，然后添加`libresolv.tbd` `SystemConfiguration.framework`, xcode9 添加的库 不勾选Target，实际上等于未引入这两个库，勾选一下就好了。
非常感谢  已解决
